! File: tests/test_so3.f90
! SPDX-License-Identifier: Apache-2.0
! Copyright (c) 2026 Jae Hoon Seo, SMI Lab, Inha University
PROGRAM test_so3
  !! reference-parity check for the Fortran SO(3) primitives (the exponential and
  !! logarithm maps and the material tangent map) against independently computed values.
  !! Reference rotation matrices were generated by
  !! the reference at four rotation vectors spanning the identity, a moderate, a
  !! large, and a pure-z rotation, and are checked to a tight 1e-12 tolerance.
  !! Also verifies the analytical identities the element relies on: exp is a
  !! proper rotation (R^T R = I, det = +1), log o exp = id below the chart
  !! boundary, and t_material(0) = I.
  !!
  !! Reference matrices are filled column-by-column (Fortran storage order):
  !! col(j) is the j-th column of the reference 3x3, so want(:, j) below lists
  !! [row1, row2, row3] of that column.
  USE CableDyn_Precision, ONLY: wp
  USE CableDyn_SO3, ONLY: CD_Hat, CD_Exp_SO3, CD_Log_SO3, CD_T_Material, &
                          CD_Dexp_SO3, CD_Dexp_Inv_SO3, CD_T_Material_Dir, &
                          CD_Dexp_Dir_SO3, CD_Compose_Rotvec, CD_T_Material_Dir2
  IMPLICIT NONE

  REAL(wp), PARAMETER :: TOL = 1.0e-12_wp
  REAL(wp), PARAMETER :: PI = 3.14159265358979323846_wp
  REAL(wp), PARAMETER :: PI_M = PI - 1.0e-4_wp           ! just below the chart boundary
  REAL(wp), PARAMETER :: SQRT3 = 1.7320508075688772_wp
  INTEGER :: nfail
  REAL(wp) :: theta(3), R(3, 3), Tm(3, 3), RtR(3, 3), det, lg(3), want(3, 3)
  REAL(wp) :: cross(3), a(3), b(3), dl(3), cmp(3)
  nfail = 0

  ! --- case 1: identity ---
  theta = [0.0_wp, 0.0_wp, 0.0_wp]
  R = CD_Exp_SO3(theta)
  CALL check_mat(R, eye3(), 'exp(0)=I')
  CALL check_mat(CD_T_Material(theta), eye3(), 'Tmat(0)=I')
  CALL check_mat(CD_Dexp_Inv_SO3(theta), eye3(), 'dexp_inv(0)=I')
  CALL check_directional_helpers(theta, [0.2_wp, -0.1_wp, 0.3_wp], 'zero')

  ! --- case 2: moderate rotation [0.3,-0.2,0.1] ---
  theta = [0.3_wp, -0.2_wp, 0.1_wp]
  want(:, 1) = [0.9752903089530457_wp, 0.06803131640494_wp, 0.21019170595074285_wp]
  want(:, 2) = [-0.12733457491763028_wp, 0.9505806179060914_wp, 0.28316496056507373_wp]
  want(:, 3) = [-0.18054007669439773_wp, -0.3029327134026371_wp, 0.9357548032779188_wp]
  R = CD_Exp_SO3(theta)
  CALL check_mat(R, want, 'exp[0.3,-0.2,0.1]')
  lg = CD_Log_SO3(R)
  CALL check_vec(lg, theta, 'log o exp [moderate]')
  want(:, 1) = [0.9917248059331613_wp, -0.059349614974115096_wp, -0.09387364774771387_wp]
  want(:, 2) = [0.039489149213702036_wp, 0.9834496118663224_wp, -0.1515682239084612_wp]
  want(:, 3) = [0.1038038806279204_wp, 0.14494806865499016_wp, 0.9784844954262192_wp]
  Tm = CD_T_Material(theta)
  CALL check_mat(Tm, want, 'Tmat[0.3,-0.2,0.1]')

  ! --- case 3: large rotation [1.2,0.5,-0.7] ---
  theta = [1.2_wp, 0.5_wp, -0.7_wp]
  want(:, 1) = [0.6925178681736104_wp, -0.22268295812275832_wp, -0.6861714817900668_wp]
  want(:, 2) = [0.7213026313547416_wp, 0.1980533588852269_wp, 0.6636997672404334_wp]
  want(:, 3) = [-0.011896060734709724_wp, -0.9545612432924235_wp, 0.29777729353162363_wp]
  R = CD_Exp_SO3(theta)
  CALL check_mat(R, want, 'exp[1.2,0.5,-0.7]')
  lg = CD_Log_SO3(R)
  CALL check_vec(lg, theta, 'log o exp [large]')
  want(:, 1) = [0.8894329410921854_wp, 0.38051044273400203_wp, 0.08224964382517647_wp]
  want(:, 2) = [-0.20121250936997837_wp, 0.7116291571728619_wp, -0.5509149037964901_wp]
  want(:, 3) = [-0.3332667505348096_wp, 0.44632444266747634_wp, 0.7474887438456668_wp]
  Tm = CD_T_Material(theta)
  CALL check_mat(Tm, want, 'Tmat[1.2,0.5,-0.7]')

  ! --- case 4: pure-z [0,0,2.5] (near-but-below pi) ---
  theta = [0.0_wp, 0.0_wp, 2.5_wp]
  want(:, 1) = [-0.8011436155469338_wp, 0.5984721441039564_wp, 0.0_wp]
  want(:, 2) = [-0.5984721441039564_wp, -0.8011436155469338_wp, 0.0_wp]
  want(:, 3) = [0.0_wp, 0.0_wp, 1.0_wp]
  R = CD_Exp_SO3(theta)
  CALL check_mat(R, want, 'exp[0,0,2.5]')
  lg = CD_Log_SO3(R)
  CALL check_vec(lg, theta, 'log o exp [pure-z]')

  ! --- analytical identities on the large case ---
  R = CD_Exp_SO3([1.2_wp, 0.5_wp, -0.7_wp])
  RtR = MATMUL(TRANSPOSE(R), R)
  CALL check_mat(RtR, eye3(), 'R^T R = I (orthogonal)')
  det = R(1, 1)*(R(2, 2)*R(3, 3) - R(2, 3)*R(3, 2)) &
        - R(1, 2)*(R(2, 1)*R(3, 3) - R(2, 3)*R(3, 1)) &
        + R(1, 3)*(R(2, 1)*R(3, 2) - R(2, 2)*R(3, 1))
  CALL require(ABS(det - 1.0_wp) < TOL, 'det(R) = +1')

  ! --- hat: hat(a).b == a x b ---
  a = [0.4_wp, -1.1_wp, 0.6_wp]
  b = [0.2_wp, 0.9_wp, -0.3_wp]
  cross = MATMUL(CD_Hat(a), b)
  CALL require(ABS(cross(1) - (a(2)*b(3) - a(3)*b(2))) < TOL .AND. &
               ABS(cross(2) - (a(3)*b(1) - a(1)*b(3))) < TOL .AND. &
               ABS(cross(3) - (a(1)*b(2) - a(2)*b(1))) < TOL, 'hat(a).b = a x b')

  ! --- near-pi log round-trip WITH axis sign (mirrors the reference
  !     implementation's test_log_inverts_exp_near_pi_with_sign: it caught the
  !     near-pi eigenvector branch returning the wrong axis sign for rotations
  !     whose dominant component is negative). Sweep |theta| just below pi on
  !     each cardinal axis in both signs, plus one mixed-sign case. ---
  CALL check_roundtrip([PI_M, 0.0_wp, 0.0_wp], 'log o exp near-pi +x')
  CALL check_roundtrip([-PI_M, 0.0_wp, 0.0_wp], 'log o exp near-pi -x')
  CALL check_roundtrip([0.0_wp, PI_M, 0.0_wp], 'log o exp near-pi +y')
  CALL check_roundtrip([0.0_wp, -PI_M, 0.0_wp], 'log o exp near-pi -y')
  CALL check_roundtrip([0.0_wp, 0.0_wp, PI_M], 'log o exp near-pi +z')
  CALL check_roundtrip([0.0_wp, 0.0_wp, -PI_M], 'log o exp near-pi -z')
  CALL check_roundtrip([-PI_M/SQRT3, PI_M/SQRT3, -PI_M/SQRT3], 'log o exp near-pi mixed-sign')

  ! --- dexp_so3 (LEFT Jacobian = T_material^T) vs reference ---
  theta = [0.3_wp, -0.2_wp, 0.1_wp]
  want(:, 1) = [0.9917248059331613_wp, 0.039489149213702036_wp, 0.1038038806279204_wp]
  want(:, 2) = [-0.059349614974115096_wp, 0.9834496118663224_wp, 0.14494806865499016_wp]
  want(:, 3) = [-0.09387364774771387_wp, -0.1515682239084612_wp, 0.9784844954262192_wp]
  CALL check_mat(CD_Dexp_SO3(theta), want, 'dexp[0.3,-0.2,0.1]')
  CALL check_mat(CD_Dexp_SO3(theta), TRANSPOSE(CD_T_Material(theta)), 'dexp = Tmat^T')
  theta = [1.2_wp, 0.5_wp, -0.7_wp]
  want(:, 1) = [0.8894329410921854_wp, -0.2012125093699784_wp, -0.3332667505348096_wp]
  want(:, 2) = [0.38051044273400203_wp, 0.711629157172862_wp, 0.4463244426674764_wp]
  want(:, 3) = [0.0822496438251765_wp, -0.5509149037964901_wp, 0.7474887438456668_wp]
  CALL check_mat(CD_Dexp_SO3(theta), want, 'dexp[1.2,0.5,-0.7]')
  CALL check_mat(MATMUL(CD_Dexp_Inv_SO3(theta), CD_Dexp_SO3(theta)), eye3(), 'dexp_inv*dexp=I')
  CALL check_directional_helpers(theta, [0.2_wp, -0.1_wp, 0.3_wp], 'large')

  ! --- directional derivatives across the small-angle cancellation band ---
  ! The dc1_ds/dc2_ds (T_material_Dir) and d2c1/d2c2 (T_material_Dir2) closed forms
  ! cancel to leading order, so they lose precision for 1e-6 < |theta| < ~0.1 unless the
  ! widened Taylor branch (DERIV_TAYLOR_SQ) is used. These points sit inside that band and
  ! fail loudly if the threshold is narrowed back to SMALL_ANGLE_SQ. (Avoid |theta| at the
  ! 0.25 switch itself, where the FD straddles the two branches and amplifies the gap.)
  CALL check_directional_helpers([1.0e-3_wp, 0.0_wp, 0.0_wp], [0.2_wp, -0.1_wp, 0.3_wp], 'band-1e-3')
  CALL check_directional_helpers([7.0e-3_wp, -4.0e-3_wp, 5.0e-3_wp], [0.2_wp, -0.1_wp, 0.3_wp], 'band-1e-2')
  CALL check_directional_helpers([0.07_wp, -0.04_wp, 0.05_wp], [0.2_wp, -0.1_wp, 0.3_wp], 'band-1e-1')
  CALL check_directional_helpers([0.13_wp, 0.09_wp, -0.11_wp], [0.2_wp, -0.1_wp, 0.3_wp], 'band-2e-1')

  ! --- branch continuity at the DERIV_TAYLOR_SQ switch (|theta| = 0.25) ---
  ! The Taylor and closed-form branches must agree across the switch so the tangent
  ! has no kink there (Newton smoothness). Evaluate just inside (Taylor) and just
  ! outside (closed form) along the same direction with |theta|^2 = 0.0625 -/+ 1e-10,
  ! so the true variation is ~2e-10 and any branch mismatch dominates a < 1e-7 gate.
  CALL check_switch_continuity()

  ! --- compose_rotvec vs reference ---
  theta = [0.3_wp, -0.2_wp, 0.1_wp]; dl = [0.05_wp, 0.02_wp, -0.03_wp]
  cmp = CD_Compose_Rotvec(theta, dl)
  CALL check_vec(cmp, [0.3475520682767383_wp, -0.18729544463749712_wp, 0.06236073745416922_wp], &
                 'compose[moderate]')
  theta = [1.2_wp, 0.5_wp, -0.7_wp]; dl = [0.1_wp, -0.08_wp, 0.05_wp]
  cmp = CD_Compose_Rotvec(theta, dl)
  CALL check_vec(cmp, [1.2996510694299097_wp, 0.5011940244257209_wp, -0.5875459124510654_wp], &
                 'compose[large]')
  ! identity: compose(theta, 0) = theta
  CALL check_vec(CD_Compose_Rotvec([0.4_wp, -0.1_wp, 0.2_wp], [0.0_wp, 0.0_wp, 0.0_wp]), &
                 [0.4_wp, -0.1_wp, 0.2_wp], 'compose[zero-increment]')
  ! identity: compose(0, dtheta) = dtheta  (mirrors test_compose_from_zero_is_dtheta)
  CALL check_vec(CD_Compose_Rotvec([0.0_wp, 0.0_wp, 0.0_wp], [0.2_wp, -0.1_wp, 0.05_wp]), &
                 [0.2_wp, -0.1_wp, 0.05_wp], 'compose[from-zero]')
  ! defining identity: exp(compose(theta, dtheta)) = exp(dtheta) exp(theta)
  ! (mirrors test_compose_matches_matrix_product)
  theta = [0.7_wp, -0.3_wp, 0.4_wp]; dl = [0.1_wp, 0.15_wp, -0.05_wp]
  cmp = CD_Compose_Rotvec(theta, dl)
  CALL check_mat(CD_Exp_SO3(cmp), MATMUL(CD_Exp_SO3(dl), CD_Exp_SO3(theta)), 'compose[matrix-product]')

  IF (nfail > 0) THEN
    WRITE (*, '(A,I0,A)') 'FAIL: ', nfail, ' assertion(s) failed'
    ERROR STOP 1
  END IF
  WRITE (*, '(A)') 'PASS: Fortran SO(3) primitives match the independent reference values'

CONTAINS

  INCLUDE 'nan_max_abs.inc'

  PURE FUNCTION eye3() RESULT(I3)
    REAL(wp) :: I3(3, 3)
    INTEGER :: k
    I3 = 0.0_wp
    DO k = 1, 3
      I3(k, k) = 1.0_wp
    END DO
  END FUNCTION eye3

  SUBROUTINE check_mat(got, want_mat, label)
    REAL(wp), INTENT(IN) :: got(3, 3), want_mat(3, 3)
    CHARACTER(*), INTENT(IN) :: label
    CALL require(nan_max_abs(got - want_mat) < TOL, label)
  END SUBROUTINE check_mat

  SUBROUTINE check_vec(got, want_vec, label)
    REAL(wp), INTENT(IN) :: got(3), want_vec(3)
    CHARACTER(*), INTENT(IN) :: label
    CALL require(nan_max_abs(got - want_vec) < TOL, label)
  END SUBROUTINE check_vec

  SUBROUTINE check_roundtrip(th, label)
    !! log_so3(exp_so3(theta)) == theta WITH the correct axis sign. The gate is
    !! 1e-7: the point of this sweep is sign disambiguation (a sign flip gives
    !! error ~2|theta| ~ 6), while the residual magnitude error ~1e-8 just below
    !! pi is the intrinsic acos conditioning limit there (the reference accepts the
    !! same -- its np.allclose carries the default rtol=1e-5, ~3e-5 effective).
    REAL(wp), INTENT(IN) :: th(3)
    CHARACTER(*), INTENT(IN) :: label
    REAL(wp) :: back(3)
    back = CD_Log_SO3(CD_Exp_SO3(th))
    CALL require(nan_max_abs(back - th) < 1.0e-7_wp, label)
  END SUBROUTINE check_roundtrip

  SUBROUTINE check_directional_helpers(th, dir, label)
    REAL(wp), INTENT(IN) :: th(3), dir(3)
    CHARACTER(*), INTENT(IN) :: label
    REAL(wp), PARAMETER :: HH = 1.0e-6_wp
    REAL(wp) :: fd(3, 3), got(3, 3)
    fd = (CD_T_Material(th + HH*dir) - CD_T_Material(th - HH*dir))/(2.0_wp*HH)
    got = CD_T_Material_Dir(th, dir)
    CALL require(nan_max_abs(got - fd) < 1.0e-7_wp, 'T_material_dir FD '//label)
    fd = (CD_Dexp_SO3(th + HH*dir) - CD_Dexp_SO3(th - HH*dir))/(2.0_wp*HH)
    got = CD_Dexp_Dir_SO3(th, dir)
    CALL require(nan_max_abs(got - fd) < 1.0e-7_wp, 'dexp_dir FD '//label)
    ! second directional derivative of T_material: D2T(th; dir, dir_b) must equal the
    ! central FD of D[T_material].dir in direction dir_b, and be symmetric in dir<->dir_b.
    BLOCK
      REAL(wp), PARAMETER :: dir_b(3) = [0.13_wp, 0.27_wp, -0.19_wp]
      REAL(wp) :: fd2(3, 3), got2(3, 3)
      fd2 = (CD_T_Material_Dir(th + HH*dir_b, dir) - CD_T_Material_Dir(th - HH*dir_b, dir))/(2.0_wp*HH)
      got2 = CD_T_Material_Dir2(th, dir, dir_b)
      CALL require(nan_max_abs(got2 - fd2) < 1.0e-7_wp, 'T_material_dir2 FD '//label)
      CALL require(nan_max_abs(got2 - CD_T_Material_Dir2(th, dir_b, dir)) < 1.0e-12_wp, &
                   'T_material_dir2 symmetric '//label)
    END BLOCK
  END SUBROUTINE check_directional_helpers

  SUBROUTINE check_switch_continuity()
    !! Directly gate continuity of CD_T_Material_Dir and CD_T_Material_Dir2 across the
    !! Taylor/closed-form switch at |theta|^2 = DERIV_TAYLOR_SQ (= 0.0625, |theta| = 0.25).
    !! Two states straddle the switch by +/- 1e-10 in |theta|^2 along the same unit axis,
    !! so the true function variation is ~2e-10; any branch mismatch (a wrong Taylor
    !! coefficient or a moved threshold leaving a cancellation gap) dominates the gate.
    REAL(wp), PARAMETER :: SW = 0.0625_wp, EPS = 1.0e-10_wp
    REAL(wp), PARAMETER :: dir_a(3) = [0.2_wp, -0.1_wp, 0.3_wp]
    REAL(wp), PARAMETER :: dir_b(3) = [0.13_wp, 0.27_wp, -0.19_wp]
    REAL(wp) :: u(3), th_lo(3), th_hi(3)
    u = [0.3713906763541037_wp, -0.7427813527082074_wp, 0.5570860145311556_wp]   ! unit axis
    th_lo = SQRT(SW - EPS)*u    ! just inside the switch -> Taylor branch
    th_hi = SQRT(SW + EPS)*u    ! just outside the switch -> closed-form branch
    CALL require(nan_max_abs(CD_T_Material_Dir(th_hi, dir_a) - CD_T_Material_Dir(th_lo, dir_a)) < 1.0e-7_wp, &
                 'T_material_dir continuous at |theta|=0.25 switch')
    CALL require(nan_max_abs(CD_T_Material_Dir2(th_hi, dir_a, dir_b) &
                             - CD_T_Material_Dir2(th_lo, dir_a, dir_b)) < 1.0e-7_wp, &
                 'T_material_dir2 continuous at |theta|=0.25 switch')
  END SUBROUTINE check_switch_continuity

  SUBROUTINE require(cond, label)
    LOGICAL, INTENT(IN) :: cond
    CHARACTER(*), INTENT(IN) :: label
    IF (.NOT. cond) THEN
      WRITE (*, '(A,A,A)') 'MISMATCH [', label, ']: condition false'
      nfail = nfail + 1
    END IF
  END SUBROUTINE require

END PROGRAM test_so3
