! File: tests/test_torsion_orcaflex.f90
! SPDX-License-Identifier: Apache-2.0
! Copyright (c) 2026 Jae Hoon Seo, SMI Lab, Inha University
!> Torsion compared with OrcaFlex 11.6d summary values (tests/data/torsion_orcaflex_refs.txt,
!> regenerated by validation/scripts/orcaflex_torsion_reference.py):
!>  a. pure torsion of a straight clamped line through the deck (L 10 m, GJ 10 kN.m^2): the
!>     torque at End A and End B for gamma_B = 90, 450, 1800 and -90 deg, gamma_A 30 / gamma_B
!>     120 deg (only the difference matters), and two sections in series (GJ 10 / 25 kN.m^2);
!>  b. Greenhill onset of the clamped-clamped line at T L^2/EI = 0, 10, 50 and 200, and of
!>     bending-pinned, torsion-restrained ends at 0 and 10 (the semi-tangential end), N = 32,
!>     against OrcaFlex extrapolated to zero segment length;
!>  c. the Lozon et al. (2025) Gulf of Mexico 80 m lazy-wave cable with an illustrative
!>     GJ = 50 kN.m^2, clamped at both ends in its untwisted static orientation and twisted
!>     0 to 5 turns at the hang-off through the deck Pretwist: hang-off torque, geometric twist
!>     Theta = Phi - M L / GJ, peak interior curvature, out-of-plane offset and hang-off tension;
!>     at zero twist the deck also reproduces the same cable without torsion columns.
!> Argument 1: tests/data/torsion_orcaflex_refs.txt.
PROGRAM test_torsion_orcaflex
  USE CableDyn_Precision, ONLY: wp
  USE CableDyn_DeckDriver, ONLY: CD_Run_Deck_Driver, CD_DECKDRV_OK
  USE CableDyn_HermiteCableStatic, ONLY: CD_HermiteCable_Static_Solve, CD_HCSTAT_OK
  USE CableDyn_HermiteTorsion, ONLY: CD_HermiteTorsionType
  USE CableDyn_EndConnection, ONLY: CD_ENDCONN_PINNED, CD_ENDCONN_RIGID
  USE, INTRINSIC :: IEEE_ARITHMETIC, ONLY: IEEE_IS_FINITE
  IMPLICIT NONE

  REAL(wp), PARAMETER :: PI = 3.14159265358979323846_wp, RHOW = 1025.0_wp
  INTEGER :: n_fail = 0, npure = 0, nclamp = 0, npin = 0, nlw = 0
  REAL(wp) :: pure(3, 8), series_ref = 0.0_wp, clamp(3, 8), pin(3, 4), orient(2) = 0.0_wp, lw(6, 8)
  CHARACTER(512) :: ref_path

  IF (COMMAND_ARGUMENT_COUNT() < 1) THEN
    WRITE (*, '(A)') 'usage: test_torsion_orcaflex <torsion_orcaflex_refs.txt>'
    ERROR STOP 2
  END IF
  CALL GET_COMMAND_ARGUMENT(1, ref_path)
  CALL read_refs()

  CALL check_pure()
  CALL check_onsets()
  CALL check_lazy_wave()

  IF (n_fail > 0) THEN
    WRITE (*, '(A,I0,A)') 'FAIL: ', n_fail, ' torsion OrcaFlex comparison(s) failed'
    ERROR STOP 1
  END IF
  WRITE (*, '(A)') 'PASS: torsion agrees with the OrcaFlex 11.6d summary values'

CONTAINS

  INCLUDE 'nan_max_abs.inc'

  SUBROUTINE require(cond, msg)
    LOGICAL, INTENT(IN) :: cond
    CHARACTER(*), INTENT(IN) :: msg
    IF (.NOT. cond) THEN
      n_fail = n_fail + 1
      WRITE (*, '(A,A)') 'FAILED: ', msg
    END IF
  END SUBROUTINE require

  SUBROUTINE read_refs()
    INTEGER :: u, ios
    CHARACTER(512) :: line
    CHARACTER(16) :: tag
    REAL(wp) :: v(6)
    OPEN (NEWUNIT=u, FILE=ref_path, STATUS='OLD', ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) THEN
      WRITE (*, '(A)') 'cannot open '//TRIM(ref_path)
      ERROR STOP 2
    END IF
    DO
      READ (u, '(A)', IOSTAT=ios) line
      IF (ios /= 0) EXIT
      IF (LEN_TRIM(line) == 0 .OR. line(1:1) == '#') CYCLE
      READ (line, *, IOSTAT=ios) tag
      IF (ios /= 0) CYCLE
      v = 0.0_wp
      SELECT CASE (TRIM(tag))
      CASE ('pure')
        READ (line, *, IOSTAT=ios) tag, v(1:3)
        IF (ios == 0 .AND. npure < SIZE(pure, 2)) THEN
          npure = npure + 1
          pure(:, npure) = v(1:3)
        END IF
      CASE ('series')
        READ (line, *, IOSTAT=ios) tag, series_ref
      CASE ('clamped')
        READ (line, *, IOSTAT=ios) tag, v(1:3)
        IF (ios == 0 .AND. nclamp < SIZE(clamp, 2)) THEN
          nclamp = nclamp + 1
          clamp(:, nclamp) = v(1:3)
        END IF
      CASE ('pinned')
        READ (line, *, IOSTAT=ios) tag, v(1:3)
        IF (ios == 0 .AND. npin < SIZE(pin, 2)) THEN
          npin = npin + 1
          pin(:, npin) = v(1:3)
        END IF
      CASE ('orientation')
        READ (line, *, IOSTAT=ios) tag, orient
      CASE ('lazywave')
        READ (line, *, IOSTAT=ios) tag, v
        IF (ios == 0 .AND. nlw < SIZE(lw, 2)) THEN
          nlw = nlw + 1
          lw(:, nlw) = v
        END IF
      END SELECT
    END DO
    CLOSE (u)
    IF (npure < 5 .OR. nclamp < 4 .OR. npin < 2 .OR. nlw < 6 .OR. series_ref <= 0.0_wp .OR. orient(1) <= 0.0_wp) THEN
      WRITE (*, '(A)') 'reference file incomplete: '//TRIM(ref_path)
      ERROR STOP 2
    END IF
  END SUBROUTINE read_refs

  SUBROUTINE write_deck(path, types, points, sections, endconns, options, outs)
    !! A one-line deck: line 1 from point 1 (End A) to point 2 (End B).
    CHARACTER(*), INTENT(IN) :: path, types(:), points(:), sections(:), endconns(:), options(:), outs(:)
    INTEGER :: u, i
    OPEN (NEWUNIT=u, FILE=path, STATUS='REPLACE', ACTION='WRITE')
    WRITE (u, '(A)') 'torsion OrcaFlex comparison deck'
    WRITE (u, '(A)') '--- LINE TYPES ---'
    WRITE (u, '(A)') 'Name Diam Mass EA BA EI GAs GJ Irt Irn Cdn Cdt Can Cat'
    WRITE (u, '(A)') '(-) (m) (kg/m) (N) (-) (Nm2) (N) (Nm2) (kgm) (kgm) (-) (-) (-) (-)'
    DO i = 1, SIZE(types)
      WRITE (u, '(A)') TRIM(types(i))
    END DO
    WRITE (u, '(A)') '--- POINTS ---'
    WRITE (u, '(A)') 'ID Type X Y Z Mass Vol CdA Ca'
    WRITE (u, '(A)') '(-) (-) (m) (m) (m) (kg) (m3) (m2) (-)'
    DO i = 1, SIZE(points)
      WRITE (u, '(A)') TRIM(points(i))
    END DO
    WRITE (u, '(A)') '--- LINES ---'
    WRITE (u, '(A)') 'ID NodeA NodeB Outputs'
    WRITE (u, '(A)') '(-) (-) (-) (-)'
    WRITE (u, '(A)') '1 1 2 -'
    WRITE (u, '(A)') '--- SECTIONS ---'
    WRITE (u, '(A)') 'LineID LineType Length NumSegs'
    WRITE (u, '(A)') '(-) (-) (m) (-)'
    DO i = 1, SIZE(sections)
      WRITE (u, '(A)') TRIM(sections(i))
    END DO
    WRITE (u, '(A)') '--- END CONNECTIONS ---'
    WRITE (u, '(A)') 'LineID End Stiffness EzX EzY EzZ TorsStiffness NxX NxY NxZ Pretwist'
    WRITE (u, '(A)') '(-) (-) (N-m/rad) (-) (-) (-) (N-m/rad) (-) (-) (-) (deg)'
    DO i = 1, SIZE(endconns)
      WRITE (u, '(A)') TRIM(endconns(i))
    END DO
    WRITE (u, '(A)') '--- OPTIONS ---'
    WRITE (u, '(A)') '9.80665 g'
    WRITE (u, '(A)') '1025.0 rhoW'
    DO i = 1, SIZE(options)
      WRITE (u, '(A)') TRIM(options(i))
    END DO
    WRITE (u, '(A)') '--- OUTPUTS ---'
    DO i = 1, SIZE(outs)
      WRITE (u, '(A)') TRIM(outs(i))
    END DO
    WRITE (u, '(A)') '--- END ---'
    CLOSE (u)
  END SUBROUTINE write_deck

  SUBROUTINE run_deck(path, root, ok, em_out)
    CHARACTER(*), INTENT(IN) :: path, root
    LOGICAL, INTENT(OUT) :: ok
    CHARACTER(*), INTENT(OUT) :: em_out
    LOGICAL :: conv
    INTEGER :: es
    CALL CD_Run_Deck_Driver(path, root, conv, es, em_out)
    ok = es == CD_DECKDRV_OK .AND. conv
  END SUBROUTINE run_deck

  SUBROUTINE read_row(path, vals, ok)
    !! The first data row of a driver .out file.
    CHARACTER(*), INTENT(IN) :: path
    REAL(wp), INTENT(OUT) :: vals(:)
    LOGICAL, INTENT(OUT) :: ok
    INTEGER :: u, ios
    CHARACTER(2048) :: buf
    ok = .FALSE.
    vals = 0.0_wp
    OPEN (NEWUNIT=u, FILE=path, STATUS='OLD', ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) RETURN
    READ (u, '(A)', IOSTAT=ios) buf
    READ (u, '(A)', IOSTAT=ios) buf
    READ (u, *, IOSTAT=ios) vals
    CLOSE (u)
    ok = ios == 0 .AND. ALL(IEEE_IS_FINITE(vals))
  END SUBROUTINE read_row

  SUBROUTINE read_profile(path, prof, n, ok)
    !! The rows of a .static.out file: LineID Node ArcLength X Y Z Tension Curvature BendMoment
    !! Declination Inclination Azimuth (prof(1:12, 1:n)).
    CHARACTER(*), INTENT(IN) :: path
    REAL(wp), ALLOCATABLE, INTENT(OUT) :: prof(:, :)
    INTEGER, INTENT(OUT) :: n
    LOGICAL, INTENT(OUT) :: ok
    INTEGER :: u, ios
    REAL(wp) :: row(12)
    CHARACTER(2048) :: buf
    ALLOCATE (prof(12, 4096))
    n = 0
    ok = .FALSE.
    OPEN (NEWUNIT=u, FILE=path, STATUS='OLD', ACTION='READ', IOSTAT=ios)
    IF (ios /= 0) RETURN
    READ (u, '(A)', IOSTAT=ios) buf
    READ (u, '(A)', IOSTAT=ios) buf
    READ (u, '(A)', IOSTAT=ios) buf
    DO
      READ (u, *, IOSTAT=ios) row
      IF (ios /= 0) EXIT
      IF (n >= SIZE(prof, 2)) EXIT
      n = n + 1
      prof(:, n) = row
    END DO
    CLOSE (u)
    ok = n > 0 .AND. ALL(IEEE_IS_FINITE(prof(:, 1:n)))
  END SUBROUTINE read_profile

  ! ------------------------------------------------------------------------------------------
  SUBROUTINE check_pure()
    !! a. Straight neutral 0.1 m line along +x, End A Coupled at x = 0, End B Fixed at x = 10,
    !!    20 elements, EA 1e8 N, GJ 1e4 N.m^2, both ends clamped and restrained in torsion with
    !!    the pretwists gamma_A and gamma_B. Output precision is 8 digits. OrcaFlex's EI of
    !!    1 kN.m^2 puts every case but -90/90 deg above the Greenhill onset (0.90 kN.m): OrcaFlex
    !!    statics stays on the straight branch there, whereas CableDyn's stability check leaves
    !!    it for the buckled shape. The torque of the straight branch does not depend on EI, so
    !!    the deck uses EI = 1e6 N.m^2, which keeps the straight line stable up to five turns.
    CHARACTER(160) :: t(2), ec(2)
    CHARACTER(24) :: secs(2)
    REAL(wp) :: v(3), mass, err
    LOGICAL :: ok
    CHARACTER(512) :: em
    INTEGER :: k, ns
    mass = RHOW*0.25_wp*PI*0.01_wp
    WRITE (t(1), '(A,ES24.16,A)') 'rodA 0.1 ', mass, ' 1.0e8 0.0 1.0e6 1.0e8 1.0e4 1.0 1.0 0 0 0 0'
    WRITE (t(2), '(A,ES24.16,A)') 'rodB 0.1 ', mass, ' 1.0e8 0.0 1.0e6 1.0e8 2.5e4 1.0 1.0 0 0 0 0'
    DO k = 1, npure + 1
      IF (k <= npure) THEN
        WRITE (ec(1), '(A,F10.3)') '1 A Rigid 1 0 0 Rigid 0 0 1 ', pure(1, k)
        WRITE (ec(2), '(A,F10.3)') '1 B Rigid 1 0 0 Rigid 0 0 1 ', pure(2, k)
        secs(1) = '1 rodA 10.0 20'
        ns = 1
      ELSE
        ec(1) = '1 A Rigid 1 0 0 Rigid 0 0 1 0'
        ec(2) = '1 B Rigid 1 0 0 Rigid 0 0 1 90'
        secs(1) = '1 rodA 4.0 8'
        secs(2) = '1 rodB 6.0 12'
        ns = 2
      END IF
      CALL write_deck('tofx_pure.dat', t, [CHARACTER(48) :: '1 Coupled 0.0 0.0 -50.0 0 0 0 0', &
                                           '2 Fixed 10.0 0.0 -50.0 0 0 0 0'], secs(1:ns), ec, &
                      [CHARACTER(24) :: '0.1 dtM', '0.0 TMax'], [CHARACTER(16) :: 'Torq1N1', 'Torq1N21'])
      CALL run_deck('tofx_pure.dat', 'tofx_pure', ok, em)
      CALL require(ok, 'a: pure torsion deck runs: '//TRIM(em))
      IF (.NOT. ok) CYCLE
      CALL read_row('tofx_pure.out', v, ok)
      CALL require(ok, 'a: output readable')
      IF (k <= npure) THEN
        err = nan_max_abs(v(2:3) - pure(3, k))/ABS(pure(3, k))
        WRITE (*, '(A,2F8.1,A,2ES16.8,A,ES16.8,A,ES9.2)') 'a: gamma_A, gamma_B ', pure(1:2, k), ' deg: Torq ', &
          v(2:3), ' OrcaFlex ', pure(3, k), ' rel. ', err
      ELSE
        err = nan_max_abs(v(2:3) - series_ref)/series_ref
        WRITE (*, '(A,2ES16.8,A,ES16.8,A,ES9.2)') 'a: two sections in series: Torq ', v(2:3), ' OrcaFlex ', &
          series_ref, ' rel. ', err
      END IF
      CALL require(err <= 1.0e-7_wp, 'a: torque equals OrcaFlex to output precision')
    END DO
  END SUBROUTINE check_pure

  ! ------------------------------------------------------------------------------------------
  SUBROUTINE check_onsets()
    !! b. EI = L = GJ = 1, EA = 1e7 (EA L^2/EI of the OrcaFlex model), N = 32; onset bisected on
    !!    the stability report of the straight state (sliding End B under the dead tension). Compared with OrcaFlex
    !!    extrapolated to zero segment length (its 200-segment value is listed alongside).
    REAL(wp) :: m, err, err200
    INTEGER :: k
    DO k = 1, nclamp
      m = onset(32, clamp(1, k), CD_ENDCONN_RIGID, clamp(3, k))
      err = (m - clamp(3, k))/clamp(3, k)
      err200 = (clamp(2, k) - clamp(3, k))/clamp(3, k)
      WRITE (*, '(A,F6.1,A,F12.7,A,F12.7,A,ES10.2,A,ES10.2,A)') 'b: clamped T L^2/EI = ', clamp(1, k), &
        ': CableDyn (N = 32) ', m, ', OrcaFlex extrapolated ', clamp(3, k), ', rel. ', err, &
        ' (OrcaFlex 200 segments ', err200, ')'
      CALL require(m > 0.0_wp .AND. ABS(err) <= 2.0e-4_wp, 'b: clamped onset within 2e-4 of OrcaFlex extrapolated')
    END DO
    DO k = 1, npin
      m = onset(32, pin(1, k), CD_ENDCONN_PINNED, pin(3, k))
      err = (m - pin(3, k))/pin(3, k)
      err200 = (pin(2, k) - pin(3, k))/pin(3, k)
      WRITE (*, '(A,F6.1,A,F12.7,A,F12.7,A,ES10.2,A,ES10.2,A)') 'b: pinned (semi-tangential) T L^2/EI = ', &
        pin(1, k), ': CableDyn (N = 32) ', m, ', OrcaFlex extrapolated ', pin(3, k), ', rel. ', err, &
        ' (OrcaFlex 200 segments ', err200, ')'
      CALL require(m > 0.0_wp .AND. ABS(err) <= 2.0e-4_wp, 'b: pinned onset within 2e-4 of OrcaFlex extrapolated')
    END DO
  END SUBROUTINE check_onsets

  REAL(wp) FUNCTION onset(ne, tension, mode, mguess) RESULT(mcr)
    INTEGER, INTENT(IN) :: ne, mode
    REAL(wp), INTENT(IN) :: tension, mguess
    REAL(wp) :: lo, hi, mid
    INTEGER :: k
    LOGICAL :: failed
    lo = 0.9_wp*mguess
    hi = 1.1_wp*mguess
    mcr = -1.0_wp
    IF (.NOT. stable_at(ne, tension, mode, lo, failed)) RETURN
    IF (stable_at(ne, tension, mode, hi, failed)) RETURN
    DO k = 1, 60
      mid = 0.5_wp*(lo + hi)
      IF (stable_at(ne, tension, mode, mid, failed)) THEN
        lo = mid
      ELSE
        hi = mid
      END IF
      IF (failed) RETURN
      IF (hi - lo <= 1.0e-8_wp*mguess) EXIT
    END DO
    mcr = 0.5_wp*(lo + hi)
  END FUNCTION onset

  LOGICAL FUNCTION stable_at(ne, tension, mode, m, failed) RESULT(stab)
    INTEGER, INTENT(IN) :: ne, mode
    REAL(wp), INTENT(IN) :: tension, m
    LOGICAL, INTENT(OUT) :: failed
    TYPE(CD_HermiteTorsionType) :: tors
    REAL(wp), ALLOCATABLE :: seed(:), l0(:), q(:), f(:), curv(:)
    REAL(wp) :: res
    INTEGER :: nd, it, es, k
    CHARACTER(512) :: em
    nd = 6*(ne + 1)
    ALLOCATE (seed(nd), l0(ne), q(nd), f(nd), curv(ne + 1))
    l0 = 1.0_wp/ne
    seed = 0.0_wp
    DO k = 0, ne
      seed(6*k + 1) = REAL(k, wp)/ne
      seed(6*k + 4) = 1.0_wp
    END DO
    f = 0.0_wp
    f(nd - 5) = tension
    tors%active = .TRUE.
    ALLOCATE (tors%gj(ne))
    tors%gj = 1.0_wp
    tors%phi = m
    tors%ends = RESHAPE([1.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 1.0_wp, 0.0_wp, 0.0_wp, &
                         0.0_wp, 0.0_wp, 1.0_wp], [3, 4])
    tors%descend = .FALSE.
    CALL CD_HermiteCable_Static_Solve(l0, [(1.0e7_wp, it=1, ne)], [(1.0_wp, it=1, ne)], [(0.0_wp, it=1, ne)], seed, &
                                      [1, 2, 3, nd - 4, nd - 3], -1.0e6_wp, 0.0_wp, 1, 60, 1.0e-7_wp, 1.0_wp, q, &
                                      curv, res, it, es, em, f_nodal=f, endconn_stiffness=[0.0_wp, 0.0_wp], &
                                      endconn_direction=RESHAPE([1.0_wp, 0.0_wp, 0.0_wp, 1.0_wp, 0.0_wp, 0.0_wp], &
                                                                [3, 2]), &
                                      endconn_mode=[mode, mode], torsion=tors)
    failed = es /= CD_HCSTAT_OK
    IF (failed) WRITE (*, '(A)') '  solve failed: '//TRIM(em)
    stab = tors%stable .AND. .NOT. failed
  END FUNCTION stable_at

  ! ------------------------------------------------------------------------------------------
  SUBROUTINE lazy_wave_deck(path, turns, with_torsion)
    !! The Gulf of Mexico 80 m cable of the OrcaFlex case, hang-off End A (Coupled, held) and
    !! anchor End B (Fixed), 0.375 m elements, both ends Rigid along the untwisted OrcaFlex end
    !! orientation (End A to End B), reference normals +y, the twist at the hang-off. OrcaFlex
    !! twists its End B (the hang-off) by gamma_B = +turns about its A->B tangent; here the
    !! hang-off is End A and its Ez points the other way, so Pretwist(A) = -360 turns and
    !! Phi = Pretwist(B) - Pretwist(A) = +360 turns: the same physical twist and torque sign.
    CHARACTER(*), INTENT(IN) :: path
    REAL(wp), INTENT(IN) :: turns
    LOGICAL, INTENT(IN) :: with_torsion
    REAL(wp) :: da, db
    CHARACTER(200) :: t(2), ec(2)
    da = orient(2)*PI/180.0_wp
    db = orient(1)*PI/180.0_wp
    ! bare 0.16 m, 36.7 kg/m; buoyancy section 0.29 m, 59.53 kg/m; EA 469 MN, EI 19.9 kN.m^2,
    ! GJ 50 kN.m^2; GAs and the rotary inertias of the circular-section closure (not used here)
    t(1) = 'bare 0.160 36.70 4.69e8 0.0 1.99e4 9.0192e7 5.0e4 0.058720 0.117440 1.2 0.1 1.0 0.0'
    t(2) = 'buoy 0.290 59.53 4.69e8 0.0 1.99e4 9.0192e7 5.0e4 0.312904 0.625808 1.2 0.1 1.0 0.0'
    IF (with_torsion) THEN
      WRITE (ec(1), '(A,ES24.16,A,ES24.16,A,F10.2)') '1 A Rigid ', SIN(da), ' 0.0 ', -COS(da), ' Rigid 0 1 0 ', &
        -360.0_wp*turns
      WRITE (ec(2), '(A,ES24.16,A,ES24.16,A)') '1 B Rigid ', SIN(db), ' 0.0 ', -COS(db), ' Rigid 0 1 0 0'
    ELSE
      WRITE (ec(1), '(A,ES24.16,A,ES24.16)') '1 A Rigid ', SIN(da), ' 0.0 ', -COS(da)
      WRITE (ec(2), '(A,ES24.16,A,ES24.16)') '1 B Rigid ', SIN(db), ' 0.0 ', -COS(db)
    END IF
    CALL write_deck(path, t, [CHARACTER(48) :: '1 Coupled 5.0 0.0 -14.0 0 0 0 0', '2 Fixed 125.0 0.0 -80.0 0 0 0 0'], &
                    [CHARACTER(24) :: '1 bare 68.114 182', '1 buoy 50.0 133', '1 bare 52.101 139'], ec, &
                    [CHARACTER(24) :: '80.0 WtrDpth', '1.0e5 kBot', '1.0e4 cBot', '0.05 dtM', '0.0 TMax'], &
                    [CHARACTER(16) :: 'FairTen1'])
    IF (with_torsion) CALL add_outputs(path)
  END SUBROUTINE lazy_wave_deck

  SUBROUTINE add_outputs(path)
    !! Append the torsion channels to the OUTPUTS of a deck written by write_deck.
    CHARACTER(*), INTENT(IN) :: path
    CHARACTER(512) :: lines(200)
    INTEGER :: u, n, ios, k
    OPEN (NEWUNIT=u, FILE=path, STATUS='OLD', ACTION='READ')
    n = 0
    DO
      READ (u, '(A)', IOSTAT=ios) lines(n + 1)
      IF (ios /= 0) EXIT
      n = n + 1
    END DO
    CLOSE (u)
    OPEN (NEWUNIT=u, FILE=path, STATUS='REPLACE', ACTION='WRITE')
    DO k = 1, n
      IF (TRIM(lines(k)) == '--- END ---') THEN
        WRITE (u, '(A)') 'Torq1N1'
        WRITE (u, '(A)') 'Torq1N455'
        WRITE (u, '(A)') 'Twist1'
      END IF
      WRITE (u, '(A)') TRIM(lines(k))
    END DO
    CLOSE (u)
  END SUBROUTINE add_outputs

  SUBROUTINE check_lazy_wave()
    REAL(wp), ALLOCATABLE :: p0(:, :), p1(:, :)
    REAL(wp) :: v(5), tq, th, kap, ymax, ten, etq, eth, ekap, ey, eten, dpos, dten, worst(5)
    INTEGER :: k, n0, n1, jlo, jhi
    LOGICAL :: ok
    CHARACTER(512) :: em
    CHARACTER(32) :: root
    ! zero twist: the same cable without torsion columns (V3 on the lazy wave)
    CALL lazy_wave_deck('tofx_lw_ref.dat', 0.0_wp, .FALSE.)
    CALL run_deck('tofx_lw_ref.dat', 'tofx_lw_ref', ok, em)
    CALL require(ok, 'c: the cable without torsion runs: '//TRIM(em))
    IF (.NOT. ok) RETURN
    CALL read_profile('tofx_lw_ref.static.out', p0, n0, ok)
    CALL require(ok .AND. n0 == 455, 'c: profile without torsion readable')
    worst = 0.0_wp
    DO k = 1, nlw
      WRITE (root, '(A,I0)') 'tofx_lw', k
      CALL lazy_wave_deck(TRIM(root)//'.dat', lw(1, k), .TRUE.)
      CALL run_deck(TRIM(root)//'.dat', TRIM(root), ok, em)
      CALL require(ok, 'c: twisted lazy-wave deck runs: '//TRIM(em))
      IF (.NOT. ok) CYCLE
      CALL read_row(TRIM(root)//'.out', v, ok)
      CALL read_profile(TRIM(root)//'.static.out', p1, n1, ok)
      CALL require(ok .AND. n1 == 455, 'c: outputs readable')
      IF (.NOT. ok) CYCLE
      tq = v(3)
      th = lw(1, k) - v(5)/360.0_wp
      jlo = 1 + NINT(0.03_wp*454)
      jhi = 1 + NINT(0.97_wp*454)
      kap = MAXVAL(p1(8, jlo:jhi))
      ymax = nan_max_abs(p1(5, 1:n1))
      ten = p1(7, 1)
      IF (lw(1, k) < 0.5_wp) THEN
        etq = ABS(tq)
        eth = ABS(th)
        dpos = nan_max_abs(p1(4:6, 1:n1) - p0(4:6, 1:n0))
        dten = nan_max_abs(p1(7, 1:n1) - p0(7, 1:n0))/MAXVAL(p0(7, 1:n0))
        WRITE (*, '(A,ES10.3,A,ES10.3,A,ES10.3,A,ES10.3)') 'c: 0 turns: torque ', tq, ' N m, Theta ', th, &
          ' turns; vs no torsion columns: position ', dpos, ' m, tension ', dten
        CALL require(etq <= 1.0e-6_wp .AND. eth <= 1.0e-9_wp, 'c: no torque and no twist at zero pretwist')
        CALL require(dpos <= 1.0e-6_wp .AND. dten <= 1.0e-6_wp, 'c: zero twist reproduces the cable without torsion')
      ELSE
        etq = ABS(tq/lw(2, k) - 1.0_wp)
        eth = ABS(th - lw(3, k))/lw(1, k)
        worst(1) = nan_max_abs([worst(1), etq])
        worst(2) = nan_max_abs([worst(2), eth])
      END IF
      ekap = ABS(kap/lw(4, k) - 1.0_wp)
      ey = ABS(ymax - lw(5, k))
      eten = ABS(ten/lw(6, k) - 1.0_wp)
      worst(3) = nan_max_abs([worst(3), ekap])
      worst(4) = nan_max_abs([worst(4), ey])
      worst(5) = nan_max_abs([worst(5), eten])
      WRITE (*, '(A,F4.1,A,2F11.3,A,2F9.5,A,2F9.6,A,2F7.3,A,2F10.1)') 'c: turns ', lw(1, k), &
        ': torque (CableDyn, OrcaFlex) ', tq, lw(2, k), ' N m; Theta ', th, lw(3, k), ' turns; peak curvature ', &
        kap, lw(4, k), ' 1/m; max|Y| ', ymax, lw(5, k), ' m; hang-off tension ', ten, lw(6, k)
      CALL require(ABS(v(3) - v(4)) <= 1.0e-6_wp*MAX(1.0_wp, ABS(v(3))), 'c: torque uniform (End A = End B)')
      IF (lw(1, k) > 0.5_wp) THEN
        CALL require(etq <= 1.0e-2_wp, 'c: hang-off torque within 1 % of OrcaFlex')
        CALL require(eth <= 1.0e-3_wp, 'c: geometric twist Theta within 1e-3 turn per imposed turn')
      END IF
      CALL require(ekap <= 1.0e-2_wp, 'c: peak interior curvature within 1 % of OrcaFlex')
      CALL require(ey <= 0.1_wp, 'c: out-of-plane offset within 0.1 m of OrcaFlex')
      CALL require(eten <= 5.0e-3_wp, 'c: hang-off tension within 0.5 % of OrcaFlex')
    END DO
    WRITE (*, '(A,ES9.2,A,ES9.2,A,ES9.2,A,F6.3,A,ES9.2)') 'c: largest differences: torque ', worst(1), &
      ', Theta per turn ', worst(2), ', peak curvature ', worst(3), ', max|Y| ', worst(4), ' m, hang-off tension ', &
      worst(5)
  END SUBROUTINE check_lazy_wave

END PROGRAM test_torsion_orcaflex
