#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Jae Hoon Seo, SMI Lab, Inha University
"""Cold-start regression for the three reference installed lazy-wave decks."""

from __future__ import annotations

import argparse
import math
import subprocess
from pathlib import Path


# OrcaFlex 11.6c static values of the same installed decks (hang-off tension [N] and peak
# curvature [1/m] of the power cables, fairlead tension [N] of the moorings; generated by
# validation/scripts/orcaflex_lozon_cables.py and orcaflex_lozon_moorings.py). CableDyn's
# cold starts land within 0.2 % of the cable values and 0.6 % of the mooring values, so
# RELATIVE_LIMIT = 1 % separates the physical branch from a wrong one without float
# brittleness.
REFERENCES = {
    "gomex80": (9.32e3, 0.0968),
    "gomaine200": (25.16e3, 0.0831),
    "humboldt800": (56.535e3, 0.02802),
}
MOORING_REFERENCES = {
    "gomex80": 747.4e3,
    "gomaine200": 1199.2e3,
    "humboldt800": 1881.5e3,
}
RELATIVE_LIMIT = 0.01
# A physical lazy wave is tensile along its length; a wrong branch folds into compression.
# The shipped decks keep every element tensile, so compression beyond 5 % of the hang-off
# tension marks the wrong branch.
COMPRESSION_LIMIT = 0.05
GOMAINE_DIAGNOSTIC_SEGMENTS = {
    "238e": (
        ("1       bare      171.978  464", "1       bare      171.978  116"),
        ("1       buoy      60.000   160", "1       buoy      60.000   40"),
        ("1       bare      121.527  328", "1       bare      121.527  82"),
    ),
    "357e": (
        ("1       bare      171.978  464", "1       bare      171.978  174"),
        ("1       buoy      60.000   160", "1       buoy      60.000   60"),
        ("1       bare      121.527  328", "1       bare      121.527  123"),
    ),
    "476e": (
        ("1       bare      171.978  464", "1       bare      171.978  232"),
        ("1       buoy      60.000   160", "1       buoy      60.000   80"),
        ("1       bare      121.527  328", "1       bare      121.527  164"),
    ),
}


def read_profile(path: Path) -> tuple[float, float, float]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 5:
        raise AssertionError(f"static profile is empty or truncated: {path}")
    names = lines[1].split()
    if names[:8] != [
        "LineID",
        "Node",
        "ArcLength",
        "X",
        "Y",
        "Z",
        "Tension",
        "Curvature",
    ]:
        raise AssertionError(f"unexpected static-profile schema: {names}")
    rows = []
    for line_number, line in enumerate(lines[3:], start=4):
        fields = line.split()
        if len(fields) != len(names):
            raise AssertionError(f"malformed static row {line_number} in {path}")
        try:
            row = [float(value.replace("D", "E").replace("d", "e")) for value in fields]
        except ValueError as exc:
            raise AssertionError(f"nonnumeric static row {line_number} in {path}") from exc
        if not all(math.isfinite(value) for value in row):
            raise AssertionError(f"non-finite static row {line_number} in {path}")
        rows.append(row)
    if not rows or int(rows[0][1]) != 1:
        raise AssertionError(f"profile does not begin at public End A: {path}")
    return rows[0][6], max(row[7] for row in rows), min(row[6] for row in rows)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--exe", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)

    for site, (reference_tension, reference_curvature) in REFERENCES.items():
        deck = args.source / "examples" / f"lozon_{site}_power_cable.dat"
        text = deck.read_text(encoding="utf-8")
        if "initialShapeFile" in text or "initial_shape" in text:
            raise AssertionError(f"{deck.name} must exercise an automatic cold start")
        root = args.output / f"lozon_cold_start_{site}"
        completed = subprocess.run(
            [str(args.exe), str(deck), str(root)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if completed.returncode:
            raise AssertionError(
                f"{deck.name} failed with exit code {completed.returncode}:\n{completed.stdout}"
            )
        tension, curvature, _minimum_tension = read_profile(root.with_suffix(".static.out"))
        tension_error = abs(tension - reference_tension) / reference_tension
        curvature_error = abs(curvature - reference_curvature) / reference_curvature
        if tension_error > RELATIVE_LIMIT or curvature_error > RELATIVE_LIMIT:
            raise AssertionError(
                f"{site} selected the wrong equilibrium branch: "
                f"tension={tension:.7g} N ({tension_error:.2%}), "
                f"peak curvature={curvature:.7g} 1/m ({curvature_error:.2%})"
            )
        print(
            f"{site}: fairlead tension {tension / 1000:.4f} kN, "
            f"peak curvature {curvature:.6f} 1/m"
        )

    # A converged residual is not enough for a bending cable: an unrestricted
    # fine-mesh Newton update can land on a folded, compression-dominated stationary
    # point while retaining a plausible fairlead tension. Exercise three coarser,
    # section-aligned meshes and require the same physical lazy-wave branch.
    source_deck = args.source / "examples" / "lozon_gomaine200_power_cable.dat"
    source_text = source_deck.read_text(encoding="utf-8")
    # The production deck reports near-sag-bend nodes on its 952-element mesh.
    # Coarser diagnostic variants need output requests that remain valid before
    # any optional safety refinement; the full static profile is assessed below.
    for marker, replacement in (
        ('"Curv1N429"', '"Curv1N1"'),
        ('"BendMom1N429"', '"BendMom1N1"'),
    ):
        if source_text.count(marker) != 1:
            raise AssertionError(f"Gulf of Maine output row changed unexpectedly: {marker!r}")
        source_text = source_text.replace(marker, replacement, 1)
    reference_tension, reference_curvature = REFERENCES["gomaine200"]
    for label, replacements in GOMAINE_DIAGNOSTIC_SEGMENTS.items():
        refined_text = source_text
        for marker, replacement in replacements:
            if refined_text.count(marker) != 1:
                raise AssertionError(
                    f"cannot construct {label} refinement: expected one {marker!r} segment count"
                )
            refined_text = refined_text.replace(marker, replacement, 1)
        refined_deck = args.output / f"lozon_gomaine200_{label}.dat"
        refined_deck.write_text(refined_text, encoding="utf-8")
        root = args.output / f"lozon_cold_start_gomaine200_{label}"
        completed = subprocess.run(
            [str(args.exe), str(refined_deck), str(root)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if completed.returncode:
            raise AssertionError(
                f"{refined_deck.name} failed with exit code {completed.returncode}:\n"
                f"{completed.stdout}"
            )
        tension, curvature, minimum_tension = read_profile(root.with_suffix(".static.out"))
        tension_error = abs(tension - reference_tension) / reference_tension
        curvature_error = abs(curvature - reference_curvature) / reference_curvature
        compression_dominated = minimum_tension < -COMPRESSION_LIMIT * tension
        if tension_error > RELATIVE_LIMIT or curvature_error > RELATIVE_LIMIT or compression_dominated:
            raise AssertionError(
                f"gomaine200 {label} refinement selected the wrong equilibrium branch: "
                f"tension={tension:.7g} N ({tension_error:.2%}), "
                f"peak curvature={curvature:.7g} 1/m ({curvature_error:.2%}), "
                f"minimum tension={minimum_tension:.7g} N"
            )
        print(
            f"gomaine200 {label}: fairlead tension {tension / 1000:.4f} kN, "
            f"peak curvature {curvature:.6f} 1/m"
        )

    # The 476-element Gulf-of-Maine mesh enters the production sequencing path. Enabling
    # adaptive diagnosis must polish that already-solved full-buoyancy state; it
    # must not replay cold-seed buoyancy continuation and collapse the selected arch.
    sequenced_text = source_text
    for marker, replacement in GOMAINE_DIAGNOSTIC_SEGMENTS["476e"]:
        sequenced_text = sequenced_text.replace(marker, replacement, 1)
    adaptive_marker = (
        "False     adaptive_mesh    - Automatic finite-EI refinement {False; True} [default: False]"
    )
    if sequenced_text.count(adaptive_marker) != 1:
        raise AssertionError(f"cannot enable adaptive mesh: {adaptive_marker!r}")
    adaptive_text = sequenced_text.replace(
        adaptive_marker,
        "True      adaptive_mesh    - Automatic finite-EI refinement {False; True} [default: False]",
        1,
    )
    adaptive_deck = args.output / "gomaine200_sequenced_adaptive_4x.dat"
    adaptive_deck.write_text(adaptive_text, encoding="utf-8")
    adaptive_root = args.output / "gomaine200_sequenced_adaptive_4x"
    completed = subprocess.run(
        [str(args.exe), str(adaptive_deck), str(adaptive_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode:
        raise AssertionError("sequenced adaptive cable failed:\n" + completed.stdout)
    adaptive_tension, _adaptive_curvature, adaptive_minimum = read_profile(
        adaptive_root.with_suffix(".static.out")
    )
    branch_error = abs(adaptive_tension - reference_tension) / abs(reference_tension)
    if branch_error > RELATIVE_LIMIT or adaptive_minimum < -COMPRESSION_LIMIT * abs(adaptive_tension):
        raise AssertionError(
            "adaptive refinement changed the sequenced equilibrium branch: "
            f"reference tension={reference_tension:.7g} N, "
            f"adaptive tension={adaptive_tension:.7g} N ({branch_error:.2%}), "
            f"adaptive minimum={adaptive_minimum:.7g} N"
        )

    # A sequence-eligible suspended cable shifted below the solver's -2000 m no-bed
    # sentinel must remain there. Supplying nodal-contact optionals accidentally turns
    # that sentinel into a real default-kBot floor and lifts the interior toward -2000 m.
    suspended_text = source_text
    for marker, replacement in GOMAINE_DIAGNOSTIC_SEGMENTS["476e"]:
        suspended_text = suspended_text.replace(marker, replacement, 1)
    for option_row in (
        "200.0    WtrDpth         - Water depth for the flat seabed (m) "
        "[default: absent standalone; host-owned OpenFAST]\n",
        "1.0e5    kBot            - Seabed penalty stiffness base (Pa/m) [default: 1.0e5]\n",
        "1.0e4    cBot            - Seabed normal damping base (Pa-s/m) [default: 1.0e4]\n",
    ):
        if suspended_text.count(option_row) != 1:
            raise AssertionError(f"Gulf of Maine contact option changed unexpectedly: {option_row!r}")
        suspended_text = suspended_text.replace(option_row, "", 1)
    deep_text = suspended_text
    for marker, replacement in (
        ("1   Coupled  5.0     0.0  -14.0", "1   Coupled  5.0     0.0  -2114.0"),
        ("2   Fixed    205.0   0.0  -200.0", "2   Fixed    205.0   0.0  -2300.0"),
    ):
        if deep_text.count(marker) != 1:
            raise AssertionError(f"Gulf of Maine endpoint row changed unexpectedly: {marker!r}")
        deep_text = deep_text.replace(marker, replacement, 1)
    deep_deck = args.output / "gomaine200_deep_suspended_4x.dat"
    deep_deck.write_text(deep_text, encoding="utf-8")
    deep_root = args.output / "gomaine200_deep_suspended_4x"
    completed = subprocess.run(
        [str(args.exe), str(deep_deck), str(deep_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode:
        raise AssertionError("deep suspended sequenced cable failed:\n" + completed.stdout)
    else:
        deep_profile_path = deep_root.with_suffix(".static.out")
        read_profile(deep_profile_path)
        deep_z = [
            float(line.split()[5])
            for line in deep_profile_path.read_text().splitlines()[3:]
        ]
        if max(deep_z) > -2050.0:
            raise AssertionError(
                "suspended sequenced cable was lifted toward the undeclared -2000 m sentinel floor"
            )

    for site, reference_tension in MOORING_REFERENCES.items():
        deck = args.source / "examples" / f"lozon_{site}_mooring.dat"
        root = args.output / f"lozon_mooring_{site}"
        completed = subprocess.run(
            [str(args.exe), str(deck), str(root)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if completed.returncode:
            raise AssertionError(
                f"{deck.name} failed with exit code {completed.returncode}:\n{completed.stdout}"
            )
        tension, _curvature, _minimum_tension = read_profile(root.with_suffix(".static.out"))
        tension_error = abs(tension - reference_tension) / reference_tension
        if tension_error > RELATIVE_LIMIT:
            raise AssertionError(
                f"{site} mooring pretension={tension:.7g} N ({tension_error:.2%})"
            )
        print(f"{site} mooring: fairlead tension {tension / 1000:.3f} kN")

    # Both standalone lifecycle families must expose progress/ETA, and the mixed
    # route must march the EI=0 system and finite-EI cable as one atomic aggregate.
    mixed_source = args.source / "examples" / "iea15mw_umaine_mixed_cabledyn.dat"
    mixed_text = mixed_source.read_text(encoding="utf-8")
    marker = "0.0      TMax"
    if mixed_text.count(marker) != 1:
        raise AssertionError("mixed example must declare one static-only TMax option")
    mixed_deck = args.output / "mixed_one_step.dat"
    mixed_deck.write_text(mixed_text.replace(marker, "0.025    TMax", 1), encoding="utf-8")
    mixed_root = args.output / "mixed_one_step"
    completed = subprocess.run(
        [str(args.exe), str(mixed_deck), str(mixed_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode:
        raise AssertionError(
            f"mixed standalone deck failed with exit code {completed.returncode}:\n"
            f"{completed.stdout}"
        )
    for required in ("mixed standalone aggregate", "Dynamic simulation:", "Progress:", "ETA"):
        if required not in completed.stdout:
            raise AssertionError(f"mixed standalone report omitted {required!r}")
    mixed_rows = mixed_root.with_suffix(".out").read_text(encoding="utf-8").splitlines()
    if len(mixed_rows) != 4:
        raise AssertionError("one-step mixed output must contain title, header, t=0, and t=dt rows")
    static_lines = mixed_root.with_suffix(".static.out").read_text(encoding="utf-8").splitlines()
    line_ids = {int(line.split()[0]) for line in static_lines[3:] if line.split()}
    if line_ids != {1, 2, 3, 4}:
        raise AssertionError(f"mixed static profile omitted a line family: {line_ids}")

    # Static equilibrium is not a time march: a mixed deck may omit both dtM and
    # TMax. The executable supplies only an internal aggregate initialization clock,
    # which must not leak into the public deck contract.
    static_mixed_text = mixed_text
    for option_row in (
        "0.025    dtM              - CableDyn internal time step (s) "
        "[default: omitted standalone; 0.1 s target OpenFAST]\n",
        "0.0      TMax             - Standalone simulation duration (s); 0 writes the initialized mixed statics "
        "[default: host-owned OpenFAST]\n",
        "0.35     frictionMu       - Coulomb seabed-friction coefficient [default: none]\n",
    ):
        if static_mixed_text.count(option_row) != 1:
            raise AssertionError(f"mixed example option row changed unexpectedly: {option_row!r}")
        static_mixed_text = static_mixed_text.replace(option_row, "", 1)
    static_mixed_deck = args.output / "mixed_static_without_clock.dat"
    static_mixed_deck.write_text(static_mixed_text, encoding="utf-8")
    static_mixed_root = args.output / "mixed_static_without_clock"
    completed = subprocess.run(
        [str(args.exe), str(static_mixed_deck), str(static_mixed_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode:
        raise AssertionError("clock-free mixed static deck failed:\n" + completed.stdout)
    if not static_mixed_root.with_suffix(".static.out").is_file():
        raise AssertionError("clock-free mixed static deck omitted its static profile")
    if static_mixed_root.with_suffix(".static.out").read_bytes() != mixed_root.with_suffix(
        ".static.out"
    ).read_bytes():
        raise AssertionError("internal static initialization clock changed the mixed equilibrium")

    # The aggregate does not yet expose the live per-line node/segment histories used
    # by the homogeneous driver's p/t files. A request must fail by name instead of
    # completing successfully while silently dropping the requested engineering data.
    output_marker = "1    1      2      -"
    if mixed_text.count(output_marker) != 1:
        raise AssertionError("mixed example line table changed unexpectedly")
    mixed_outputs_deck = args.output / "mixed_line_outputs_rejected.dat"
    mixed_outputs_deck.write_text(
        mixed_text.replace(output_marker, "1    1      2      p", 1), encoding="utf-8"
    )
    completed = subprocess.run(
        [str(args.exe), str(mixed_outputs_deck), str(args.output / "mixed_line_outputs_rejected")],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode != 1 or "mixed-deck LINE Outputs p/t" not in completed.stdout:
        raise AssertionError(
            "mixed per-line output request did not fail closed by name:\n" + completed.stdout
        )

    held_root = args.output / "driver_progress_held"
    completed = subprocess.run(
        [str(args.exe), str(args.source / "examples" / "dynamic_chain_held.dat"), str(held_root)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if completed.returncode:
        raise AssertionError(
            f"held dynamic progress case failed with exit code {completed.returncode}:\n"
            f"{completed.stdout}"
        )
    if "Dynamic simulation:" not in completed.stdout or "100.0%" not in completed.stdout:
        raise AssertionError("homogeneous standalone dynamics omitted progress reporting")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
