# SPDX-License-Identifier: Apache-2.0
"""The CableDyn project object model: typed objects, units, commands and adapters.

:mod:`cabledyn.project` describes a complete CableDyn model as a graph of
plain Python objects, without any GUI toolkit:

* :class:`ModelObject` subclasses with typed, unit-aware property
  descriptors (:class:`Quantity`, :class:`Ref`, :class:`Children`, ...),
  each flagged ``physics`` (written to the deck), ``construction``,
  ``appearance`` or ``meta``;
* references between objects instead of names or ids, with safe rename and
  cascading removal (:mod:`cabledyn.project.references`);
* change events (:mod:`cabledyn.project.events`) and undoable commands on a
  :class:`CommandStack` (:mod:`cabledyn.project.commands`);
* three validation layers (:mod:`cabledyn.project.validation`);
* an SI units layer with display preferences (:mod:`cabledyn.project.units`);
* the deck adapters :class:`DeckReader` and :class:`DeckWriter`, built on
  :class:`cabledyn.DeckModel`, and the ``.cdproj`` :class:`ProjectStore`.

Examples
--------
>>> from cabledyn.project import DeckReader, DeckWriter, ProjectStore
>>> project = DeckReader.read("examples/spread_3line_chain.dat")  # doctest: +SKIP
>>> project.lines[0].sections[0].length = 850.0  # doctest: +SKIP
>>> ProjectStore.save(project, "spread.cdproj")  # doctest: +SKIP
>>> DeckWriter(project).write("spread.dat")  # doctest: +SKIP
"""

from __future__ import annotations

from cabledyn.project.appearance import (
    CableAppearance,
    ChainAppearance,
    EnvironmentAppearance,
    FibreRopeAppearance,
    LineAppearance,
    MeshAsset,
    ModuleGeometry,
    PlainLineAppearance,
    SeabedAppearance,
    WireRopeAppearance,
)
from cabledyn.project.base import (
    REGISTRY,
    ModelObject,
    SerialContext,
    TypeRegistry,
    UnknownTypeError,
    model_type,
)
from cabledyn.project.bodies import Body, Floater, Point3Body, Rigid6Body, Turbine
from cabledyn.project.collection import ObjectCollection
from cabledyn.project.commands import (
    AddObject,
    ApplyLibraryItem,
    Command,
    CommandStack,
    ImportDeck,
    MacroCommand,
    MoveInCollection,
    Reconnect,
    RemoveObject,
    ReplaceStrategy,
    SetProperty,
    SplitSection,
    StackChanged,
)
from cabledyn.project.deck import DeckExportError, DeckReader, DeckWriter, IdMap
from cabledyn.project.descriptors import (
    Bool,
    Child,
    Children,
    Choice,
    Colour,
    FilePath,
    Integer,
    JsonValue,
    OptionalBool,
    OptionalColour,
    OptionalInteger,
    OptionalQuantity,
    OptionalText,
    OptionalVec3,
    Property,
    Quantity,
    Ref,
    RefList,
    Role,
    Strategy,
    Text,
    TextList,
    Vec3,
    Vector,
)
from cabledyn.project.environment import (
    BathymetrySeabed,
    CurrentModel,
    Environment,
    FlatSeabed,
    FloaterMotionRecord,
    FloaterRAO,
    JonswapWave,
    MotionFile,
    MotionSource,
    MultiTrainSea,
    NoCurrent,
    NoMotion,
    NoWaves,
    OchiHubbleWave,
    ProfileCurrent,
    RegularWave,
    Seabed,
    SpectrumWave,
    UniformCurrent,
    WaveModel,
    WaveTrain,
)
from cabledyn.project.events import (
    ChildAdded,
    ChildMoved,
    ChildRemoved,
    Event,
    EventHub,
    PropertyChanged,
    ReferenceChanged,
    Subscription,
)
from cabledyn.project.issues import Issue, Severity
from cabledyn.project.lines import (
    Attachment,
    BendRestrictor,
    BendStiffener,
    BuoyancyModule,
    ClumpWeight,
    EndConnection,
    Line,
    LineAncillary,
    Section,
    TouchdownProtection,
)
from cabledyn.project.points import (
    BodyPoint,
    ConnectPoint,
    FixedPoint,
    FloaterPoint,
    FreePoint,
    LineEndTarget,
    Point,
    RodEndpoint,
    RodPoint,
    TurbinePoint,
)
from cabledyn.project.project import Project
from cabledyn.project.references import ObjectInUseError, RemovalPlan, plan_removal, referrers
from cabledyn.project.rods import Rod
from cabledyn.project.rows import (
    Channel,
    Control,
    EquivalentBuoyancy,
    ExternalLoad,
    Failure,
    NamedChannel,
    ObjectChannel,
    OutputRequest,
    SyropeIC,
)
from cabledyn.project.settings import AnalysisSettings, ExtraOption
from cabledyn.project.store import SCHEMA_VERSION, ProjectFormatError, ProjectStore
from cabledyn.project.studio import CameraBookmark, Group, StudioData
from cabledyn.project.types import (
    AxialModel,
    BendingModel,
    CableType,
    ChainType,
    FibreRopeType,
    FloaterType,
    GenericLineType,
    HydroDatabase,
    HydroDatabaseFile,
    LinearAxial,
    LineType,
    NoHydroDatabase,
    RodType,
    SyropeAxial,
    ViscoelasticAxial,
    WireRopeType,
)
from cabledyn.project.units import Dimension, Unit, UnitError, UnitSystem
from cabledyn.project.validation import validate_project

__all__ = [
    "REGISTRY",
    "SCHEMA_VERSION",
    "AddObject",
    "AnalysisSettings",
    "ApplyLibraryItem",
    "Attachment",
    "AxialModel",
    "BathymetrySeabed",
    "BendRestrictor",
    "BendStiffener",
    "BendingModel",
    "Body",
    "BodyPoint",
    "Bool",
    "BuoyancyModule",
    "CableAppearance",
    "CableType",
    "CameraBookmark",
    "ChainAppearance",
    "ChainType",
    "Channel",
    "Child",
    "ChildAdded",
    "ChildMoved",
    "ChildRemoved",
    "Children",
    "Choice",
    "ClumpWeight",
    "Colour",
    "Command",
    "CommandStack",
    "ConnectPoint",
    "Control",
    "CurrentModel",
    "DeckExportError",
    "DeckReader",
    "DeckWriter",
    "Dimension",
    "EndConnection",
    "Environment",
    "EnvironmentAppearance",
    "EquivalentBuoyancy",
    "Event",
    "EventHub",
    "ExternalLoad",
    "ExtraOption",
    "Failure",
    "FibreRopeAppearance",
    "FibreRopeType",
    "FilePath",
    "FixedPoint",
    "FlatSeabed",
    "Floater",
    "FloaterMotionRecord",
    "FloaterPoint",
    "FloaterRAO",
    "FloaterType",
    "FreePoint",
    "GenericLineType",
    "Group",
    "HydroDatabase",
    "HydroDatabaseFile",
    "IdMap",
    "ImportDeck",
    "Integer",
    "Issue",
    "JonswapWave",
    "JsonValue",
    "Line",
    "LineAncillary",
    "LineAppearance",
    "LineEndTarget",
    "LineType",
    "LinearAxial",
    "MacroCommand",
    "MeshAsset",
    "ModelObject",
    "ModuleGeometry",
    "MotionFile",
    "MotionSource",
    "MoveInCollection",
    "MultiTrainSea",
    "NamedChannel",
    "NoCurrent",
    "NoHydroDatabase",
    "NoMotion",
    "NoWaves",
    "ObjectChannel",
    "ObjectCollection",
    "ObjectInUseError",
    "OchiHubbleWave",
    "OptionalBool",
    "OptionalColour",
    "OptionalInteger",
    "OptionalQuantity",
    "OptionalText",
    "OptionalVec3",
    "OutputRequest",
    "PlainLineAppearance",
    "Point",
    "Point3Body",
    "ProfileCurrent",
    "Project",
    "ProjectFormatError",
    "ProjectStore",
    "Property",
    "PropertyChanged",
    "Quantity",
    "Reconnect",
    "Ref",
    "RefList",
    "ReferenceChanged",
    "RegularWave",
    "RemovalPlan",
    "RemoveObject",
    "ReplaceStrategy",
    "Rigid6Body",
    "Rod",
    "RodEndpoint",
    "RodPoint",
    "RodType",
    "Role",
    "Seabed",
    "SeabedAppearance",
    "Section",
    "SerialContext",
    "SetProperty",
    "Severity",
    "SpectrumWave",
    "SplitSection",
    "StackChanged",
    "Strategy",
    "StudioData",
    "Subscription",
    "SyropeAxial",
    "SyropeIC",
    "Text",
    "TextList",
    "TouchdownProtection",
    "Turbine",
    "TurbinePoint",
    "TypeRegistry",
    "UniformCurrent",
    "Unit",
    "UnitError",
    "UnitSystem",
    "UnknownTypeError",
    "Vec3",
    "Vector",
    "ViscoelasticAxial",
    "WaveModel",
    "WaveTrain",
    "WireRopeAppearance",
    "WireRopeType",
    "model_type",
    "plan_removal",
    "referrers",
    "validate_project",
]
