# SPDX-License-Identifier: Apache-2.0
"""Readers for OpenFAST, MoorDyn, and OpenFAST-coupled CableDyn output files."""

from __future__ import annotations

import functools
import struct
import tracemalloc
import warnings
from pathlib import Path
from time import perf_counter

import numpy as np
import pytest

from cabledyn import (
    MoorDynLineHistory,
    OutputFormatError,
    StaticProfile,
    TimeHistory,
    read_coupled_run,
    read_moordyn_line,
    read_moordyn_output,
    read_openfast_output,
    read_table,
)
from cabledyn import results as results_module
from cabledyn._paths import windows_device_component
from cabledyn.post_cli import main as post_main

# Layout written by OpenFAST (NWTC_IO, tab-separated, title lines, units row).
OPENFAST_TEXT = (
    "\n"
    "Predictions were generated on 05-Feb-2026 at 19:16:44 using OpenFAST\n"
    " linked with  NWTC Subroutine Library; ElastoDyn\n"
    "\n"
    "Description from the FAST input file: Time looks like a header word here\n"
    "\n"
    "Time\tRotSpeed\tRootMyc1\n"
    "(s)\t(rpm)\t(kN-m)\n"
    "    0.0000\t0.00000000\t1426.06262\n"
    "    0.0500\t0.10000000\t0.141260262E+04\n"
    "    0.1000\t0.20000000\t-0.126390868E-12\n"
)

# MoorDyn-F layouts (MoorDyn_IO.f90): a banner, blank lines, then header and units.
MOORDYN_MAIN = (
    "\n"
    "These predictions were generated by MoorDyn (v2.3.8) on 31-Mar-2026 at 20:14:13.\n"
    "\n \n \n \n"
    "      Time        FAIRTEN1       FAIRTEN2\n"
    "       (s)             (N)             (N)\n"
    "    0.0000   1.8761071E+06   5.6970426E+04\n"
    "    0.5000   1.8762071E+06   5.6980426E+04\n"
)


def _moordyn_line(nodes: int = 3, *, extra: str = "", drop: str | None = None) -> str:
    names = ["Time"]
    units = ["(s)"]
    for node in range(nodes):
        for axis in "xyz":
            names.append(f"Node{node}p{axis}")
            units.append("(m)")
    for segment in range(1, nodes):
        names.append(f"Seg{segment}Ten")
        units.append("(N)")
    if extra:
        names.append(extra)
        units.append("(-)")
    if drop is not None:
        index = names.index(drop)
        del names[index], units[index]
    rows = []
    for step in range(3):
        row = [0.5 * step]
        for node in range(nodes):
            row.extend([10.0 * node + step, 0.0, -50.0 + 10.0 * node])
        row.extend(1.0e5 + 10.0 * segment + step for segment in range(1, nodes))
        if extra:
            row.append(1.0)
        if drop is not None:
            del row[index]
        rows.append("  ".join(f"{value: .7E}" for value in row))
    return "  ".join(names) + "\n" + "  ".join(units) + "\n" + "\n".join(rows) + "\n"


def _write_outb(
    path: Path,
    file_id: int,
    time: np.ndarray,
    data: np.ndarray,
    names: list[str],
    units: list[str],
    *,
    name_length: int = 10,
    trailing: bytes = b"",
    description: str = "Synthetic binary",
) -> None:
    """Write an OpenFAST binary file following NWTC_IO WrBinFAST."""
    samples, channels = data.shape
    parts = [struct.pack("<h", file_id)]
    if file_id == 4:
        parts.append(struct.pack("<h", name_length))
    parts.append(struct.pack("<ii", channels, samples))
    if file_id == 1:
        time_scale, time_offset = 1.0e4, 0.0
        parts.append(struct.pack("<dd", time_scale, time_offset))
    else:
        parts.append(struct.pack("<dd", time[0], time[1] - time[0]))
    if file_id != 3:
        low, high = data.min(axis=0), data.max(axis=0)
        span = np.where(high > low, high - low, 1.0)
        scale = (65535.0 / span).astype(np.float32)
        offset = (-32768.0 - low * scale).astype(np.float32)
        parts.append(scale.tobytes())
        parts.append(offset.tobytes())
    encoded = description.encode("latin-1")
    parts.append(struct.pack("<i", len(encoded)))
    parts.append(encoded)
    for text in [*names, *units]:
        parts.append(text.ljust(name_length)[:name_length].encode("latin-1"))
    if file_id == 1:
        parts.append(np.round(time * time_scale + time_offset).astype("<i4").tobytes())
    if file_id == 3:
        parts.append(data.astype("<f8").tobytes())
    else:
        packed = np.clip(np.round(data * scale + offset), -32768, 32767).astype("<i2")
        parts.append(packed.tobytes())
    path.write_bytes(b"".join(parts) + trailing)


@pytest.fixture
def binary_series() -> tuple[np.ndarray, np.ndarray]:
    time = np.arange(0.0, 2.0, 0.05)
    data = np.column_stack((np.sin(time), 1.0e6 + 1.0e4 * np.cos(3.0 * time)))
    return time, data


def test_openfast_text_output_reads_title_units_and_values(tmp_path):
    path = tmp_path / "run.out"
    path.write_text(OPENFAST_TEXT, encoding="utf-8")
    table = read_openfast_output(path)
    assert isinstance(table, TimeHistory)
    assert table.channels == ("Time", "RotSpeed", "RootMyc1")
    assert table.unit("RootMyc1") == "kN-m"
    assert "Description from the FAST input file" in table.title
    assert np.allclose(table.column("RootMyc1"), [1426.06262, 1412.60262, -1.26390868e-13])
    assert read_table(path).channels == table.channels


# An OutList that requests TwrBsFzt twice, as the r-test IEA-15MW ElastoDyn file does, and
# already uses the suffix the second repeat would take.
OPENFAST_REPEATED = (
    "Predictions were generated by OpenFAST\n"
    "\n"
    "Time\tTwrBsFzt\tRotSpeed\tTwrBsFzt\tTwrBsFzt_3\tTwrBsFzt\n"
    "(s)\t(kN)\t(rpm)\t(kN)\t(kN)\t(kN)\n"
    "0.0\t-1.0\t5.0\t-2.0\t-3.0\t-4.0\n"
    "0.1\t-1.5\t5.1\t-2.5\t-3.5\t-4.5\n"
)


def test_openfast_text_output_keeps_repeated_channels(tmp_path):
    path = tmp_path / "repeat.out"
    path.write_text(OPENFAST_REPEATED, encoding="utf-8")
    with pytest.warns(UserWarning, match=r"repeat\.out:3: .*TwrBsFzt -> TwrBsFzt_2") as caught:
        table = read_openfast_output(path)
    assert len(caught) == 1
    assert "TwrBsFzt -> TwrBsFzt_4" in str(caught[0].message)
    assert table.channels == (
        "Time",
        "TwrBsFzt",
        "RotSpeed",
        "TwrBsFzt_2",
        "TwrBsFzt_3",
        "TwrBsFzt_4",
    )
    assert np.array_equal(table.column("TwrBsFzt"), [-1.0, -1.5])  # first occurrence
    assert np.array_equal(table.column("TwrBsFzt_2"), [-2.0, -2.5])
    assert np.array_equal(table.column("TwrBsFzt_3"), [-3.0, -3.5])  # the file's own column
    assert np.array_equal(table.column("TwrBsFzt_4"), [-4.0, -4.5])
    assert table.unit("TwrBsFzt_4") == "kN"
    # The same file through read_table (the CableDyn reader) and a unique file: no warning.
    with pytest.warns(UserWarning, match="TwrBsFzt_2"):
        assert read_table(path).channels == table.channels
    unique = tmp_path / "unique.out"
    unique.write_text(OPENFAST_TEXT, encoding="utf-8")
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        read_openfast_output(unique)


def test_coupled_run_reads_an_openfast_output_with_repeated_channels(tmp_path):
    root = tmp_path / "IEA15"
    _write_coupled(root)
    Path(f"{root}.out").write_text(OPENFAST_REPEATED, encoding="utf-8")
    with pytest.warns(UserWarning, match="TwrBsFzt_2"):
        run = read_coupled_run(root)
    assert run.openfast is not None
    assert run.openfast.channels.count("TwrBsFzt") == 1
    assert np.array_equal(run.openfast.column("TwrBsFzt"), [-1.0, -1.5])
    assert run.cabledyn is not None and run.cabledyn.channels == ("Time", "FairTen1", "AnchTen1")


@pytest.mark.parametrize("file_id", [1, 2, 3, 4])
def test_openfast_binary_formats_decode_to_the_written_series(tmp_path, binary_series, file_id):
    time, data = binary_series
    path = tmp_path / "run.outb"
    _write_outb(
        path,
        file_id,
        time,
        data,
        ["Time", "Wave1Elev", "FairTen1"],
        ["(s)", "(m)", "(N)"],
        name_length=12 if file_id == 4 else 10,
    )
    table = read_openfast_output(path)
    assert table.channels == ("Time", "Wave1Elev", "FairTen1")
    assert table.units == ("(s)", "(m)", "(N)")
    assert table.title == "Synthetic binary"
    assert np.allclose(table.time, time, atol=1.0e-9)
    # int16 packing keeps each channel to 1/65535 of its range; float64 is exact.
    tolerance = 0.0 if file_id == 3 else 1.0 / 65535.0
    for index, channel in enumerate(("Wave1Elev", "FairTen1")):
        span = float(np.ptp(data[:, index]))
        assert np.max(np.abs(table.column(channel) - data[:, index])) <= tolerance * span + 1e-12
    assert type(read_table(path)) is TimeHistory


def test_openfast_binary_units_without_parentheses_are_normalized(tmp_path, binary_series):
    time, data = binary_series
    path = tmp_path / "bare.outb"
    _write_outb(path, 2, time, data, ["Time", "A", "B"], ["s", "m", "N"])
    assert read_openfast_output(path).units == ("(s)", "(m)", "(N)")


@pytest.mark.parametrize(
    ("mutation", "message"),
    [
        (lambda raw: raw[:-3], "truncated"),
        (lambda raw: raw + b"\0\0", "trailing bytes"),
        (lambda raw: struct.pack("<h", 9) + raw[2:], "format identifier 9"),
        (lambda raw: raw[:2] + struct.pack("<i", 0) + raw[6:], "declares 0 channels"),
        (lambda raw: raw[:1], "truncated"),
    ],
)
def test_openfast_binary_corruption_fails_closed(tmp_path, binary_series, mutation, message):
    time, data = binary_series
    path = tmp_path / "bad.outb"
    _write_outb(path, 2, time, data, ["Time", "A", "B"], ["(s)", "(m)", "(N)"])
    path.write_bytes(mutation(path.read_bytes()))
    with pytest.raises(OutputFormatError, match=message):
        read_openfast_output(path)


def _outb_header(file_id: int, channels: int, samples: int, *, name_length: int = 10) -> bytes:
    """A binary header, one scale/offset pair, and one short name pair; no data."""
    parts = [struct.pack("<h", file_id)]
    if file_id == 4:
        parts.append(struct.pack("<h", name_length))
    parts.append(struct.pack("<ii", channels, samples))
    parts.append(struct.pack("<dd", 1.0 if file_id == 1 else 0.0, 0.1))
    if file_id != 3:
        parts.append(struct.pack("<ff", 1.0, 0.0))
    parts.append(struct.pack("<i", 0))
    parts.append(b"Time      Chan1     (s)       (-)       ")
    return b"".join(parts)


@pytest.mark.parametrize(
    ("file_id", "channels", "samples", "name_length"),
    [
        (2, 1, 300_000_000, 10),
        (1, 1, 2**31 - 1, 10),
        (3, 2**31 - 1, 1, 10),
        (3, 1, 2**31 - 1, 10),
        (4, 1, 1, 32767),
        (4, 65535, 65535, 2),
    ],
)
def test_openfast_binary_declared_sizes_are_checked_before_allocating(
    tmp_path, file_id, channels, samples, name_length
):
    path = tmp_path / "huge.outb"
    path.write_bytes(_outb_header(file_id, channels, samples, name_length=name_length))
    tracemalloc.start()
    start = perf_counter()
    try:
        with pytest.raises(OutputFormatError, match="truncated: the header declares"):
            read_openfast_output(path)
        elapsed = perf_counter() - start
        peak = tracemalloc.get_traced_memory()[1]
    finally:
        tracemalloc.stop()
    assert elapsed < 5.0
    assert peak < 16 * 2**20


def test_openfast_binary_non_finite_or_overflowing_time_factors_fail_closed(
    tmp_path, binary_series
):
    time, data = binary_series
    path = tmp_path / "time.outb"
    _write_outb(path, 2, time, data, ["Time", "A", "B"], ["(s)", "(m)", "(N)"])
    raw = bytearray(path.read_bytes())
    raw[10:18] = struct.pack("<d", float("inf"))
    path.write_bytes(bytes(raw))
    with pytest.raises(OutputFormatError, match="time scale and offset must be finite"):
        read_openfast_output(path)
    raw[10:26] = struct.pack("<dd", 1.0e308, 1.0e308)
    path.write_bytes(bytes(raw))
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        with pytest.raises(OutputFormatError, match="values must be finite"):
            read_openfast_output(path)


def test_non_utf8_text_output_is_a_format_error(tmp_path):
    for name in ("run.out", "run.MD.out", "run.MD.Line1.out"):
        path = tmp_path / name
        path.write_bytes(b"Time A\n(s) (m)\n0 \xff\n")
        with pytest.raises(OutputFormatError, match="cannot read") as caught:
            read_table(path)
        assert isinstance(caught.value.__cause__, UnicodeDecodeError)


def test_reserved_windows_device_names_are_rejected_by_every_reader(tmp_path, monkeypatch):
    monkeypatch.setattr(
        results_module,
        "windows_device_component",
        functools.partial(windows_device_component, windows=True),
    )
    for name in ("aux.outb", "con.out", "nul.MD.out", "PRN.MD.Line1.out"):
        with pytest.raises(OutputFormatError, match="reserved Windows device name"):
            read_table(tmp_path / name)


def test_moordyn_line_huge_indices_are_not_line_channels(tmp_path):
    path = tmp_path / "run.MD.Line1.out"
    path.write_text(f"Time Node{'1' * 5000}px\n0 1\n", encoding="ascii")
    with pytest.raises(OutputFormatError, match="is not a MoorDyn line channel"):
        read_moordyn_line(path)


def test_openfast_binary_keeps_repeated_names_and_rejects_zero_scales(tmp_path, binary_series):
    time, data = binary_series
    path = tmp_path / "dup.outb"
    _write_outb(path, 3, time, data, ["Time", "A", "A"], ["(s)", "(m)", "(m)"])
    with pytest.warns(UserWarning, match=r"A -> A_2"):
        table = read_openfast_output(path)
    assert table.channels == ("Time", "A", "A_2")
    assert np.array_equal(table.column("A"), data[:, 0])
    assert np.array_equal(table.column("A_2"), data[:, 1])
    _write_outb(path, 2, time, data, ["Time", "A", ""], ["(s)", "(m)", "(m)"])
    with pytest.raises(OutputFormatError, match="non-empty"):
        read_openfast_output(path)
    _write_outb(path, 2, time, data, ["Time", "A", "B"], ["(s)", "(m)", "(N)"])
    raw = bytearray(path.read_bytes())
    raw[2 + 8 + 16 : 2 + 8 + 16 + 4] = struct.pack("<f", 0.0)
    path.write_bytes(bytes(raw))
    with pytest.raises(OutputFormatError, match="scale factors"):
        read_openfast_output(path)
    _write_outb(path, 1, time, data, ["Time", "A", "B"], ["(s)", "(m)", "(N)"])
    raw = bytearray(path.read_bytes())
    raw[10:18] = struct.pack("<d", 0.0)
    path.write_bytes(bytes(raw))
    with pytest.raises(OutputFormatError, match="time scale"):
        read_openfast_output(path)


def test_openfast_binary_non_increasing_time_fails(tmp_path, binary_series):
    time, data = binary_series
    path = tmp_path / "flat.outb"
    _write_outb(path, 2, np.zeros_like(time), data, ["Time", "A", "B"], ["(s)", "(m)", "(N)"])
    with pytest.raises(OutputFormatError, match="not strictly increasing"):
        read_openfast_output(path)


def test_unreadable_files_fail_closed(tmp_path):
    with pytest.raises(OutputFormatError, match="cannot read"):
        read_openfast_output(tmp_path / "missing.outb")
    with pytest.raises(OutputFormatError, match="cannot read"):
        read_moordyn_output(tmp_path / "missing.MD.out")
    binary = tmp_path / "binary.out"
    binary.write_bytes(b"\xff\xfe\x00junk")
    with pytest.raises(OutputFormatError, match="cannot read"):
        read_openfast_output(binary)


@pytest.mark.parametrize(
    ("text", "message"),
    [
        ("", "no Time channel"),
        ("Node Value\n1 2\n", "no Time channel"),
        ("Time A A\n0 1 2\n", "duplicate channel"),
        ("Time A\n(s) (m) (x)\n0 1\n", "expected 2 units"),
        ("Time A\n(s) (m)\n0 1 2\n", "expected 2 fields"),
        ("Time A\n(s) (m)\n", "no data rows"),
        ("Time A\n0 1\n0 2\n", "not strictly increasing"),
        ("Time A\n0 inf\n", "nonnumeric|non-finite"),
    ],
)
def test_moordyn_main_output_is_strict(tmp_path, text, message):
    path = tmp_path / "run.MD.out"
    path.write_text(text, encoding="utf-8")
    with pytest.raises(OutputFormatError, match=message):
        read_moordyn_output(path)


def test_moordyn_main_output_keeps_moordyn_names(tmp_path):
    path = tmp_path / "run.MD.out"
    path.write_text(MOORDYN_MAIN, encoding="utf-8")
    table = read_moordyn_output(path)
    assert table.channels == ("Time", "FAIRTEN1", "FAIRTEN2")
    assert table.unit("FAIRTEN1") == "N"
    assert "MoorDyn" in table.title
    assert read_table(path).channels == table.channels


def test_moordyn_line_file_positions_and_tensions(tmp_path):
    path = tmp_path / "run.MD.Line1.out"
    path.write_text(_moordyn_line(), encoding="utf-8")
    line = read_moordyn_line(path)
    assert isinstance(line, MoorDynLineHistory)
    assert isinstance(read_table(path), MoorDynLineHistory)
    assert line.quantities == ("p", "Ten")
    assert (line.node_count, line.segment_count) == (3, 2)
    xyz = line.positions(0.25)
    assert xyz.shape == (3, 3)
    assert np.allclose(xyz[:, 0], [0.5, 10.5, 20.5])
    assert not xyz.flags.writeable
    assert np.allclose(line.segment_tensions(0.5), [1.0e5 + 11.0, 1.0e5 + 21.0])
    with pytest.raises(KeyError, match="'v' node channels"):
        line.node_vectors("v", 0.0)
    with pytest.raises(KeyError, match="'Str' segment"):
        line.segment_values("Str", 0.0)
    with pytest.raises(ValueError, match="unknown MoorDyn node vector"):
        line.node_vectors("q", 0.0)
    with pytest.raises(ValueError, match="unknown MoorDyn segment"):
        line.segment_values("Force", 0.0)
    trimmed = line.period(0.5, 1.0)
    assert isinstance(trimmed, MoorDynLineHistory)
    assert trimmed.segment_count == 2


def test_moordyn_line_with_node_scalars_only(tmp_path):
    names = ["Time", "Node0Kurv", "Node1Kurv", "Node2Kurv"]
    path = tmp_path / "k.MD.Line2.out"
    path.write_text(" ".join(names) + "\n0 0 0.1 0\n1 0 0.2 0\n", encoding="utf-8")
    line = read_moordyn_line(path)
    assert line.quantities == ("Kurv",)
    assert (line.node_count, line.segment_count) == (3, 2)


@pytest.mark.parametrize(
    ("kwargs", "message"),
    [
        ({"extra": "Node0Force"}, "not a MoorDyn line channel"),
        ({"drop": "Node1py"}, "all three components|different node counts"),
        ({"drop": "Seg1Ten"}, "Seg1..SegN"),
        ({"extra": "Node5Kurv"}, "different node counts|Node0..NodeN"),
    ],
)
def test_moordyn_line_file_structure_is_validated(tmp_path, kwargs, message):
    path = tmp_path / "bad.MD.Line1.out"
    path.write_text(_moordyn_line(**kwargs), encoding="utf-8")
    with pytest.raises(OutputFormatError, match=message):
        read_moordyn_line(path)


def test_moordyn_line_structure_edge_cases(tmp_path):
    path = tmp_path / "gap.MD.Line1.out"
    path.write_text("Time Node0Kurv Node2Kurv\n0 1 2\n", encoding="utf-8")
    with pytest.raises(OutputFormatError, match=r"Node0..NodeN"):
        read_moordyn_line(path)
    path.write_text("Time Node0Kurv Node1Kurv Seg1Ten Seg2Ten\n0 1 2 3 4\n", encoding="utf-8")
    with pytest.raises(OutputFormatError, match="inconsistent"):
        read_moordyn_line(path)
    path.write_text("Time\n0\n1\n", encoding="utf-8")
    with pytest.raises(OutputFormatError, match="no line channels"):
        read_moordyn_line(path)
    path.write_text("Time Seg1Ten Seg2Ten\n0 1 2\n", encoding="utf-8")
    assert read_moordyn_line(path).node_count == 3
    path.write_text("Time Seg1Ten Seg1Ten\n0 1 2\n", encoding="utf-8")
    with pytest.raises(OutputFormatError, match="duplicate"):
        read_moordyn_line(path)


def _write_coupled(root: Path, *, text: bool = True, binary: bool = False) -> None:
    Path(f"{root}.CD.out").write_text(
        "Time\tFairTen1\tAnchTen1\n(s)\t(N)\t(N)\n"
        "  0.0000000E+00\t  1.000000E+06\t  9.000000E+05\n"
        "  1.0000000E-01\t  1.100000E+06\t  9.100000E+05\n",
        encoding="utf-8",
    )
    Path(f"{root}.CD.static.out").write_text(
        "CableDyn coupled static configuration (deformed arc; public node order End A -> End B)\n"
        "LineID\tNode\tArcLength\tX\tY\tZ\tTension\tCurvature\tBendMoment\tDeclination"
        "\tInclination\tAzimuth\n"
        "(-)\t(-)\t(m)\t(m)\t(m)\t(m)\t(N)\t(1/m)\t(N.m)\t(deg)\t(deg)\t(deg)\n"
        "1\t1\t0.0\t-800.0\t0.0\t-200.0\t9.0E+05\t0.0\t0.0\t0.0\t0.0\t0.0\n"
        "1\t2\t850.0\t-58.0\t0.0\t-14.0\t1.0E+06\t0.0\t0.0\t0.0\t60.0\t0.0\n",
        encoding="utf-8",
    )
    if text:
        Path(f"{root}.out").write_text(OPENFAST_TEXT, encoding="utf-8")
    if binary:
        time = np.arange(0.0, 1.0, 0.1)
        _write_outb(
            Path(f"{root}.outb"),
            2,
            time,
            np.column_stack((time, time**2)),
            ["Time", "A", "B"],
            ["(s)", "(m)", "(m)"],
        )


def test_coupled_run_gathers_cabledyn_static_and_openfast_outputs(tmp_path):
    root = tmp_path / "IEA15"
    _write_coupled(root)
    run = read_coupled_run(f"{root}.fst")
    assert run.root == root
    assert run.cabledyn is not None and run.cabledyn.channels == ("Time", "FairTen1", "AnchTen1")
    assert run.cabledyn.unit("FairTen1") == "N"
    assert isinstance(run.static, StaticProfile)
    assert run.static.summary(1).maximum_tension == 1.0e6
    assert run.openfast is not None and "RotSpeed" in run.openfast.channels


def test_coupled_run_binary_and_ambiguous_outputs(tmp_path):
    root = tmp_path / "bin"
    _write_coupled(root, text=False, binary=True)
    assert read_coupled_run(root).openfast.channels == ("Time", "A", "B")  # type: ignore[union-attr]
    Path(f"{root}.out").write_text(OPENFAST_TEXT, encoding="utf-8")
    with pytest.raises(OutputFormatError, match="both"):
        read_coupled_run(root)


def test_coupled_run_partial_and_missing_outputs(tmp_path):
    root = tmp_path / "only"
    Path(f"{root}.CD.out").write_text("Time FairTen1\n(s) (N)\n0 1\n", encoding="utf-8")
    run = read_coupled_run(root)
    assert run.static is None and run.openfast is None
    with pytest.raises(FileNotFoundError, match="no OpenFAST or CableDyn outputs"):
        read_coupled_run(tmp_path / "absent")
    bad = tmp_path / "bad"
    Path(f"{bad}.CD.static.out").write_text("Time A\n0 1\n", encoding="utf-8")
    with pytest.raises(OutputFormatError, match="not a line profile"):
        read_coupled_run(bad)


def test_read_table_formats(tmp_path):
    path = tmp_path / "anything.txt"
    path.write_text(MOORDYN_MAIN, encoding="utf-8")
    assert read_table(path, format="moordyn").channels[1] == "FAIRTEN1"
    assert read_table(path, format="cabledyn").channels[1] == "FAIRTEN1"
    with pytest.raises(ValueError, match="format must be one of"):
        read_table(path, format="orcaflex")


def test_post_cli_reads_other_formats_and_compares(tmp_path, capsys):
    main = tmp_path / "run.MD.out"
    main.write_text(MOORDYN_MAIN, encoding="utf-8")
    assert post_main(["summary", str(main)]) == 0
    assert "FAIRTEN1" in capsys.readouterr().out
    line = tmp_path / "run.MD.Line1.out"
    line.write_text(_moordyn_line(), encoding="utf-8")
    assert post_main(["summary", str(line), "--format", "moordyn-line"]) == 0
    capsys.readouterr()
    other = tmp_path / "other.out"
    other.write_text(MOORDYN_MAIN.replace("1.8762071E+06", "1.8772071E+06"), encoding="utf-8")
    report = tmp_path / "compare.csv"
    assert (
        post_main(
            [
                "compare",
                str(main),
                str(other),
                "--format",
                "moordyn",
                "--channel",
                "FAIRTEN1",
                "--channel",
                "FAIRTEN2=FAIRTEN2",
                "--output",
                str(report),
            ]
        )
        == 0
    )
    out = capsys.readouterr().out
    assert "max_abs_difference: 1000.0" in out
    assert report.read_text(encoding="utf-8").startswith("channel,candidate_channel,unit")


def test_moordyn_vector_quantities_need_all_three_components(tmp_path):
    names = ["Time"] + [f"Node{node}p{axis}" for node in range(2) for axis in "xz"]
    path = tmp_path / "two.MD.Line1.out"
    path.write_text(" ".join(names) + "\n0 0 0 1 1\n", encoding="utf-8")
    with pytest.raises(OutputFormatError, match="needs all three components"):
        read_moordyn_line(path)


def test_text_tables_skip_blank_rows_and_need_data(tmp_path):
    path = tmp_path / "gaps.MD.out"
    path.write_text("Time A\n(s) (m)\n0 1\n\n   \n1 2\n", encoding="utf-8")
    assert read_moordyn_output(path).values.shape == (2, 2)
    path.write_text("Title\nTime A", encoding="utf-8")
    with pytest.raises(OutputFormatError, match="no data rows"):
        read_moordyn_output(path)


def test_openfast_binary_non_finite_values_fail_closed(tmp_path, binary_series):
    time, data = binary_series
    data = data.copy()
    data[3, 1] = np.nan
    path = tmp_path / "nan.outb"
    _write_outb(path, 3, time, data, ["Time", "A", "B"], ["(s)", "(m)", "(N)"])
    with pytest.raises(OutputFormatError, match="values must be finite"):
        read_openfast_output(path)


def test_moordyn_line_with_node_accelerations(tmp_path):
    # MoorDyn-F writes Node<J>ax/ay/az for the 'a' output flag
    names = ["Time"] + [f"Node{node}a{axis}" for node in range(3) for axis in "xyz"]
    path = tmp_path / "acc.MD.Line1.out"
    rows = "\n".join(" ".join(str(0.5 * step + value) for value in range(10)) for step in range(2))
    path.write_text(" ".join(names) + "\n" + rows + "\n", encoding="utf-8")
    line = read_moordyn_line(path)
    assert line.quantities == ("a",)
    assert line.node_vectors("a", 0.0).shape == (3, 3)
